<?php
	if(isset($_GET['mail']) && $_GET['mail'] != '') {
		$mail = $_GET['mail'];
	}
?>
<div style="width:850px !important;margin:0 auto;"><table cellspacing="0" cellpadding="0" width="850" border="0" align="center" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin:auto;" id="wrapper"><tbody><tr><td width="700" valign="top" style="background-color:#F1F1F1"><table style="border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt;margin-left:10px;" width="700"><tbody><tr><td><a style="border:none" href="http://www.devicemed.fr/"><img width="700" height="91" title="logo" alt="newsletter" src="http://www.device-med.fr/wp-content/uploads/newsletter/original.jpg"></a></td></tr></tbody></table><table style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;margin-left:10px;margin-top:10px;margin-bottom:10px;" width="700" id="top_news"><tbody><tr><td align="center"><a target="_blank" href="http://www.device-med.fr/?url=http://www.medteceurope.com/fr/france&amp;id=45"><img src="http://devicemed.fr/wp-content/uploads/banniere/vaisala_horizontale.jpg" border="0" alt="" style="width:468px;text-align:center;"></a></td></tr> </tbody></table>

<table style="border-collapse:collapse;border-top:1px dotted #555;mso-table-lspace:0pt; mso-table-rspace:0pt;margin-left:10px;margin-top:10px;" width="700" id="top_news"><tbody><tr><td align="left"><h1 style="font-size:20px;color:#000000;font-family:Arial;">Sommaire de la newsletter du 2 juin 2015</h1></td></tr> </tbody></table><table width="700" style="border-bottom:0;border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:10px;" id="inhaltsverzeichnis"><tbody><tr><td><ul style="padding-left:20px;margin-top:0px;margin-bottom:0;">

<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/metrologie_controle-sous-traitance-et-services/le-cetim-investit-dans-les-essais-dedies-aux-dispositifs-medicaux/3410" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Cetim&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/metrologie_controle-sous-traitance-et-services/le-cetim-investit-dans-les-essais-dedies-aux-dispositifs-medicaux/3410" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Le Cetim investit dans les essais dédiés aux dispositifs médicaux</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/une-solution-de-vision-pour-mieux-controler-le-conditionnement-de-cartouches-injectables/3404" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Keyence&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/une-solution-de-vision-pour-mieux-controler-le-conditionnement-de-cartouches-injectables/3404" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Une solution de vision pour mieux contrôler le conditionnement de cartouches injectables</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/microscope-inverse-polyvalent-et-evolutif/3450" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Leica Microsystems&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/microscope-inverse-polyvalent-et-evolutif/3450" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Microscope inversé polyvalent et évolutif</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/metrologie_controle-sous-traitance-et-services/bien-classifier-son-dm-pour-des-essais-transformes/3445" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Emitech&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/metrologie_controle-sous-traitance-et-services/bien-classifier-son-dm-pour-des-essais-transformes/3445" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Bien classifier son DM pour des essais «&nbsp;transformés&nbsp;»</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/projecteur-numerique-automatise-pour-des-mesures-optiques-2d-fiabilisees/3417" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Carl Zeiss&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/projecteur-numerique-automatise-pour-des-mesures-optiques-2d-fiabilisees/3417" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Projecteur numérique automatisé pour des mesures 2D fiabilisées</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/capteur-de-contraste-laser-haute-vitesse/3398" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Banner Engineering&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/capteur-de-contraste-laser-haute-vitesse/3398" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Capteur de contraste laser haute vitesse</span></a></li><!---->

</ul></td></tr></tbody></table>

<table width="700" style="margin-top:10px;border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:10px;" id="content"><tbody>

<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/metrologie_controle-sous-traitance-et-services/le-cetim-investit-dans-les-essais-dedies-aux-dispositifs-medicaux/3410" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/05/Cetim.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/metrologie_controle-sous-traitance-et-services/le-cetim-investit-dans-les-essais-dedies-aux-dispositifs-medicaux/3410" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Cetim</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/metrologie_controle-sous-traitance-et-services/le-cetim-investit-dans-les-essais-dedies-aux-dispositifs-medicaux/3410" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Le Cetim investit dans les essais dédiés aux dispositifs médicaux</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Référence française de l’expertise mécanique, le Cetim est de plus en plus souvent associé à des projets relatifs aux DM. Le centre technique s’est notamment impliqué dans la conception d’un dispositif de lutte contre l’obésité, [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/metrologie_controle-sous-traitance-et-services/le-cetim-investit-dans-les-essais-dedies-aux-dispositifs-medicaux/3410" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/une-solution-de-vision-pour-mieux-controler-le-conditionnement-de-cartouches-injectables/3404" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/05/Keyence.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/une-solution-de-vision-pour-mieux-controler-le-conditionnement-de-cartouches-injectables/3404" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Keyence</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/une-solution-de-vision-pour-mieux-controler-le-conditionnement-de-cartouches-injectables/3404" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Une solution de vision pour mieux contrôler le conditionnement de cartouches injectables</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Laboratoire spécialisé dans les produits dentaires, Septodont avait besoin d’améliorer le contrôle du conditionnement de ses cartouches d’anesthésique injectable. Il a opté pour le système de vision de la société Keyence, qui s’est aussi impliquée [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/une-solution-de-vision-pour-mieux-controler-le-conditionnement-de-cartouches-injectables/3404" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td colspan="2" style="border-top:1px dotted #555;padding-left:90px;"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;margin-top:10px;"><span style="font-size:12px;font-family:Helvetica,Arial,sans-serif;color:#999;">Annonce</span></p></td></tr><tr><td colspan="2" width="128" valign="top" style="width:128px;padding-bottom: 10px;padding-left:90px;">

<div style="padding:10px;width:500px;border:1px solid #333;">

<a href="http://www.device-med.fr/?url=http://www.vaisala.fr/fr/lifescience/continuous-monitoring/Pages/default.aspx?utm_medium=referral&amp;utm_source=DeviceMed&amp;utm_campaign=CEN-LSC-EMEA-FR-Device%20Med&amp;utm_content=CMS&amp;id=43" target="_blank"><img style="border:solid 1px #FFFFFF;padding-right:10px;" width="100" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/banniere/vaisela_nl_26-05-2015.jpg"></a>

<p style="margin:0px;padding-left:140px;"><a style="margin:0px;text-decoration:none;" href="http://www.device-med.fr/?url=http://www.vaisala.fr/fr/lifescience/continuous-monitoring/Pages/default.aspx?utm_medium=referral&amp;utm_source=DeviceMed&amp;utm_campaign=CEN-LSC-EMEA-FR-Device%20Med&amp;utm_content=CMS&amp;id=43" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:black;">Monitoring pour les environnements contrôlés</span></a></p>

<p style="padding-left:140px;font-size:12px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Conçu pour les environnements contrôlés dans les industries de santé, le Système de Monitoring Vaisala fournit en continu des données de température, humidité et autres paramètres tout en garantissant la totale conformité réglementaire. 

Pour plus d’informations visitez nous sur <a style="text-decoration:none;" href="http://www.device-med.fr/?url=http://www.medteceurope.com/fr/france&amp;id=44" target="_blank">Medtec France</a> ou <a style="text-decoration:none;" href="http://www.device-med.fr/?url=http://www.vaisala.fr/fr/lifescience/continuous-monitoring/Pages/default.aspx?utm_medium=referral&amp;utm_source=DeviceMed&amp;utm_campaign=CEN-LSC-EMEA-FR-Device%20Med&amp;utm_content=CMS&amp;id=43" target="_blank">cliquez ici</a>.

</p></div></td></tr>

<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/microscope-inverse-polyvalent-et-evolutif/3450" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/05/Leica-Microsystems.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/microscope-inverse-polyvalent-et-evolutif/3450" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Leica Microsystems</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/microscope-inverse-polyvalent-et-evolutif/3450" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Microscope inversé polyvalent et évolutif</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Leica propose un microscope inversé modulaire, personnalisable et capable d’évoluer de l’imagerie de base vers des applications plus élaborées comme la microscopie avancée par fluorescence.

Fabricant allemand de microscopes et d’instruments scientifiques, Leica Microsystems propose un [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/microscope-inverse-polyvalent-et-evolutif/3450" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/metrologie_controle-sous-traitance-et-services/bien-classifier-son-dm-pour-des-essais-transformes/3445" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/05/Emitech.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/metrologie_controle-sous-traitance-et-services/bien-classifier-son-dm-pour-des-essais-transformes/3445" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Emitech</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/metrologie_controle-sous-traitance-et-services/bien-classifier-son-dm-pour-des-essais-transformes/3445" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Bien classifier son DM pour des essais «&nbsp;transformés&nbsp;»</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Emitech, spécialiste français des essais sur les DM électriques et électroniques avant marquage CE, propose son assistance aux fabricants en amont du projet. L’objectif : éviter les erreurs de classification du dispositif et par là-même [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/metrologie_controle-sous-traitance-et-services/bien-classifier-son-dm-pour-des-essais-transformes/3445" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/projecteur-numerique-automatise-pour-des-mesures-optiques-2d-fiabilisees/3417" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/05/Zeiss.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/projecteur-numerique-automatise-pour-des-mesures-optiques-2d-fiabilisees/3417" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Carl Zeiss</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/projecteur-numerique-automatise-pour-des-mesures-optiques-2d-fiabilisees/3417" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Projecteur numérique automatisé pour des mesures 2D fiabilisées</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Les visiteurs du salon EPHJ-EPMT-SMT pourront découvrir cette semaine le nouveau projecteur numérique de Zeiss. Cet équipement de mesure 2D se distingue par une automatisation poussée des mesures, mais aussi de la génération des programmes.
Si [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/projecteur-numerique-automatise-pour-des-mesures-optiques-2d-fiabilisees/3417" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/capteur-de-contraste-laser-haute-vitesse/3398" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/05/Banner-Engineering2.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/capteur-de-contraste-laser-haute-vitesse/3398" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Banner Engineering</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/capteur-de-contraste-laser-haute-vitesse/3398" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Capteur de contraste laser haute vitesse</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Banner Engineering annonce un capteur de contraste laser permettant d’effectuer jusqu’à 2&nbsp;000 détections par seconde sur des pièces présentant une réflectivité peu contrastée.
Distribué en France par Turck Banner S.A.S, Banner Engineering fabrique des capteurs de [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/capteur-de-contraste-laser-haute-vitesse/3398" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>

</tbody></table><!----><table width="704" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:0px" id="footer"><tbody><tr><td style="font-family:Arial; font-size:12px"><table cellspacing="0" width="702"><tbody><tr><td style="padding-bottom:10px;padding-top:10px;padding-left:10px;padding-right:10px;background-color:#c7c7c7"><table width="700"><tbody><tr><td align="left"><a href="http://news.vogel.de/inxmail2/d?q00wueoq0eqfngbii000000000000000ietwqbri3277"><img src="http://www.devicemed.fr/wp-content/themes/devicemed-responsive/images/newsletter/nl20/vogel_logo.gif" alt="Vogel Logo"></a></td><td align="right"></td></tr></tbody></table></td></tr><!----><tr><td align="center" style="font-size:11px;font-family:Arial,Helvetica,sans-serif;padding:10px;background-color:#d2d2d2;text-align:center;"><a style="text-decoration:none;" href="http://www.devicemed.fr/nous-contacter"><span style="font-size:12px;color:#b30f1d;text-align:center;">Contact</span></a></td></tr><!----><tr><td style="PADDING-BOTTOM: 10px; PADDING-TOP: 10px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; BACKGROUND-COLOR: #616161"><p style="FONT-SIZE: 11px; FONT-FAMILY: Arial, Helvetica, sans-serif; COLOR: #ffffff; LINE-HEIGHT: 18px">© The French language edition of DeviceMed is a publication of Evelyne Gisselbrecht, licensed by Vogel Business Media GmbH &amp; Co. KG, 97082 Wuerzburg/Germany.<br>

© Copyright of the trademark « DeviceMed » by Vogel Business Media GmbH &amp; Co. KG, 97082 Wuerzburg/Germany.<br>

Responsable du contenu rédactionnel sur <a style="text-decoration:none;color:#fff;" href="http://www.devicemed.fr/">www.devicemed.fr</a> : Evelyne Gisselbrecht, éditrice de DeviceMed, 33 rue du Puy-de-Dôme, 63370 Lempdes France</p></td></tr></tbody></table><!----><p></p></td></tr><tr><td style="text-align:center;font-family:Arial;font-size:11px">Le bulletin est adressé à <?php echo $mail; ?></td></tr>

<tr style="font-family:Arial;font-size:11px;color:#005ea8;text-decoration:underline;text-align:center;"><td><a style="text-decoration:none;" href="http://www.devicemed.fr/newsletter/desinscrire/<?php echo $mail; ?>"><span>Se désabonner</span></a></td></tr></tbody></table></td><td width="10" valign="top"></td><td width="160" valign="top"><table style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;"><tbody><tr><td style="padding-bottom:10px;"><a target="_blank" href="http://www.device-med.fr/?url=http://forms.vaisala.com/LP=1385&amp;id=46"><img src="http://www.device-med.fr/wp-content/uploads/banniere/vaisala_vertical.jpg" width="127px"></a></td></tr>

<tr><td><div style="width:100%;padding-top:15px;"><a href="http://www.devicemed.fr/wp-content/uploads/archives/pdf/003_gesamt.pdf" target="_blank">

<img width="127px" src="http://devicemed.fr/wp-content/uploads/newsletter/pave_magazine.png"></a></div></td></tr></tbody></table></td></tr></tbody></table></div>