<?php
	if(isset($_GET['mail']) && $_GET['mail'] != '') {
		$mail = $_GET['mail'];
	}
?>
<div style="width:850px !important;margin:0 auto;"><table cellspacing="0" cellpadding="0" width="850" border="0" align="center" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin:auto;" id="wrapper"><tbody><tr><td width="700" valign="top" style="background-color:#F1F1F1"><table style="border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt;margin-left:10px;" width="700"><tbody><tr><td><a style="border:none" href="http://www.devicemed.fr/"><img width="700" height="91" title="logo" alt="newsletter" src="http://www.device-med.fr/wp-content/uploads/newsletter/original.jpg"></a></td></tr></tbody></table>

<table style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;margin-left:10px;margin-top:10px;" width="700" id="top_news"><tbody><tr><td align="left"><h1 style="font-size:20px;color:#000000;font-family:Arial;">Sommaire de la newsletter du 17 mars 2015</h1></td></tr> </tbody></table><table width="700" style="border-bottom:0;border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:10px;" id="inhaltsverzeichnis"><tbody><tr><td><ul style="padding-left:20px;margin-top:0px;margin-bottom:0;">

<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/sous-traitance-et-fabrication-additive-3d-au-coeur-du-congres-implants-a-paris-le-16-juin-2015/2643" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;">Vert Com&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/sous-traitance-et-fabrication-additive-3d-au-coeur-du-congres-implants-a-paris-le-16-juin-2015/2643" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Sous-traitance et fabrication additive au cœur du Congrès Implants, à Paris le 16 juin 2015</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/co2-supercritique-une-approche-ecologique-pour-le-nettoyage-de-dm/2646" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;">Pierre Fabre&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/co2-supercritique-une-approche-ecologique-pour-le-nettoyage-de-dm/2646" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">CO2 supercritique : pour nettoyer les DM écologiquement</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/materiaux/la-fibre-de-carbone-tombe-a-peek-pour-reparer-les-fractures/2702" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;">Invibio&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/materiaux/la-fibre-de-carbone-tombe-a-peek-pour-reparer-les-fractures/2702" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">La fibre de carbone tombe à PEEK pour réparer les fractures</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/est-il-pertinent-de-programmer-ses-machines-outils-avec-le-logiciel-esprit/2653" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;">DP Technology&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/est-il-pertinent-de-programmer-ses-machines-outils-avec-le-logiciel-esprit/2653" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Est-il pertinent de programmer ses machines-outils avec le logiciel Esprit ?</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/materiaux/un-materiau-detancheite-qui-glisse-dans-senflammer/2630" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;">Bal Seal Engineering&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/materiaux/un-materiau-detancheite-qui-glisse-dans-senflammer/2630" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Un matériau d’étanchéité qui glisse sans s’enflammer</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/un-laboratoire-de-metrologie-dedie-aux-dm-en-plastique/2670" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;">Précis &amp; Mans&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/un-laboratoire-de-metrologie-dedie-aux-dm-en-plastique/2670" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Un laboratoire de métrologie dédié aux DM en plastique</span></a></li><!---->

</ul></td></tr></tbody></table>

<table width="700" style="margin-top:10px;border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:10px" id="content"><tbody>

<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/sous-traitance-et-fabrication-additive-3d-au-coeur-du-congres-implants-a-paris-le-16-juin-2015/2643" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/03/Avicenne.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/sous-traitance-et-fabrication-additive-3d-au-coeur-du-congres-implants-a-paris-le-16-juin-2015/2643" target="_blank"><span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Vert Com</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/sous-traitance-et-fabrication-additive-3d-au-coeur-du-congres-implants-a-paris-le-16-juin-2015/2643" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Sous-traitance et fabrication additive au cœur du Congrès Implants, à Paris le 16 juin 2015</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Comment les sous-traitants de l’orthopédie peuvent-ils se positionner sur un marché qui évolue sur le plan des matériaux, de la réglementation, des technologies… et qui doit faire face à la concurrence de nouveaux entrants ? [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/sous-traitance-et-fabrication-additive-3d-au-coeur-du-congres-implants-a-paris-le-16-juin-2015/2643" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/co2-supercritique-une-approche-ecologique-pour-le-nettoyage-de-dm/2646" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/03/Pierre-Fabre.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/co2-supercritique-une-approche-ecologique-pour-le-nettoyage-de-dm/2646" target="_blank"><span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Pierre Fabre</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/co2-supercritique-une-approche-ecologique-pour-le-nettoyage-de-dm/2646" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">CO2 supercritique : pour nettoyer les DM écologiquement</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Connue pour son activité dans la pré-formulation de principes actifs, la division «&nbsp;Fluides Supercritiques&nbsp;» du groupe Pierre Fabre élargit ses activités de prestations aux nettoyage d’implants et de composants pour DM à base de CO2 [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/co2-supercritique-une-approche-ecologique-pour-le-nettoyage-de-dm/2646" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td colspan="2" style="border-top:1px dotted #555;padding-left:90px;"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;margin-top:10px;"><span style="font-size:12px;font-family:Helvetica,Arial,sans-serif;color:#999;">Annonce</span></p></td></tr><tr><td colspan="2" width="128" valign="top" style="width:128px;padding-bottom: 10px;padding-left:90px;">

<div style="padding:10px;width:500px;border:1px solid #333;">

<a href="http://www.device-med.fr/?url=http://www.qosina.com/catalog/part.asp?partno=80191&amp;%20utm_source=VogelBusinessMedia&amp;%20utm_medium=online%2Bad&amp;%20utm_term=%20March&amp;%20utm_content=%20image&amp;%20utm_campaign=M1325&amp;id=22" target="_blank"><img style="border:solid 1px #FFFFFF;" width="100" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/newsletter/M1325.jpg"></a>

<p style="margin:0px;padding-left:140px;"><a style="margin:0px;text-decoration:none;" href="http://www.device-med.fr/?url=http://www.qosina.com/catalog/part.asp?partno=80191&amp;%20utm_source=VogelBusinessMedia&amp;%20utm_medium=online%2Bad&amp;%20utm_term=%20March&amp;%20utm_content=%20image&amp;%20utm_campaign=M1325&amp;id=22" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:black;">Valve de transfert préfendue et tamponnnable</span></a></p>

<p style="padding-left:140px;font-size:12px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Proposée par Qosina, cette valve de transfert en silicone stérilisable est destinée à l’injection ou l’aspiration à l’aide d’une seringue avec embout pour cathéter. Adaptée à des tubes de 8,18 mm de diamètre intérieur et 13,59 mm de diamètre extérieur, elle répond notamment aux besoins de drainage impliquant de gros volumes ou des substances visqueuses. Qosina dispose aussi d’un large éventail de seringues, de tubes et de sites d’injection sans aiguille. <a style="text-decoration:none;" href="http://www.device-med.fr/?url=http://www.qosina.com/catalog/part.asp?partno=80191&amp;%20utm_source=VogelBusinessMedia&amp;%20utm_medium=online%2Bad&amp;%20utm_term=%20March&amp;%20utm_content=%20image&amp;%20utm_campaign=M1325&amp;id=22" target="_blank"><span style="color:#005ea8;">Pour en savoir plus</span></a></p></div></td></tr>

<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/materiaux/la-fibre-de-carbone-tombe-a-peek-pour-reparer-les-fractures/2702" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/03/Invibio.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/materiaux/la-fibre-de-carbone-tombe-a-peek-pour-reparer-les-fractures/2702" target="_blank"><span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Invibio</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/materiaux/la-fibre-de-carbone-tombe-a-peek-pour-reparer-les-fractures/2702" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">La fibre de carbone tombe à PEEK pour réparer les fractures</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Stable et résistant à l’usure, le PEEK implantable a de quoi séduire les fabricants d’implants. Spécialiste de ce type de polymère, Invibio y a intégré des fibres de carbone, pour déboucher sur une alternative très [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/materiaux/la-fibre-de-carbone-tombe-a-peek-pour-reparer-les-fractures/2702" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/est-il-pertinent-de-programmer-ses-machines-outils-avec-le-logiciel-esprit/2653" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/03/DP-Technology-2.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/est-il-pertinent-de-programmer-ses-machines-outils-avec-le-logiciel-esprit/2653" target="_blank"><span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">DP Technology</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/est-il-pertinent-de-programmer-ses-machines-outils-avec-le-logiciel-esprit/2653" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Est-il pertinent de programmer ses machines-outils avec le logiciel Esprit ?</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Tout dépend bien sûr des cas de figure, mais il est intéressant de considérer le retour d’expérience du site français de Stryker Spine. Neuf ans après avoir investi dans le logiciel de programmation globale Esprit, [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/est-il-pertinent-de-programmer-ses-machines-outils-avec-le-logiciel-esprit/2653" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/materiaux/un-materiau-detancheite-qui-glisse-dans-senflammer/2630" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/03/Bal-Seal.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/materiaux/un-materiau-detancheite-qui-glisse-dans-senflammer/2630" target="_blank"><span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Bal Seal Engineering</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/materiaux/un-materiau-detancheite-qui-glisse-dans-senflammer/2630" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Un matériau d’étanchéité qui glisse sans s’enflammer</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Idéal pour une utilisation dans les compresseurs de gaz et les systèmes intensificateurs d’oxygène, le SP191 répond au besoin croissant d’étanchéité à faible coefficient de friction dans des environnements à haute température.
Spécialisé dans les matériaux [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/materiaux/un-materiau-detancheite-qui-glisse-dans-senflammer/2630" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/un-laboratoire-de-metrologie-dedie-aux-dm-en-plastique/2670" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/03/Précis-Mans.png"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/un-laboratoire-de-metrologie-dedie-aux-dm-en-plastique/2670" target="_blank"><span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Précis &amp; Mans</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/un-laboratoire-de-metrologie-dedie-aux-dm-en-plastique/2670" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Un laboratoire de métrologie dédié aux DM en plastique</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Laboratoire de métrologie spécialisé dans le contrôle dimensionnel, Précis &amp; Mans se réorganise pour proposer à ses clients de nouvelles prestations en plasturgie : des études de rhéologie jusqu’à la validation sur presses électriques.
Historiquement centre [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/un-laboratoire-de-metrologie-dedie-aux-dm-en-plastique/2670" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>

</tbody></table><!----><table width="704" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:0px" id="footer"><tbody><tr><td style="font-family:Arial; font-size:12px"><table cellspacing="0" width="702"><tbody><tr><td style="padding-bottom:10px;padding-top:10px;padding-left:10px;padding-right:10px;background-color:#c7c7c7"><table width="700"><tbody><tr><td align="left"><a href="http://news.vogel.de/inxmail2/d?q00wueoq0eqfngbii000000000000000ietwqbri3277"><img src="http://www.devicemed.fr/wp-content/themes/devicemed-responsive/images/newsletter/nl20/vogel_logo.gif" alt="Vogel Logo"></a></td><td align="right"></td></tr></tbody></table></td></tr><!----><tr><td align="center" style="font-size:11px;font-family:Arial,Helvetica,sans-serif;padding:10px;background-color:#d2d2d2;text-align:center;"><a style="text-decoration:none;" href="http://www.devicemed.fr/nous-contacter"><span style="font-size:12px;color:#b30f1d;text-align:center;">Contact</span></a></td></tr><!----><tr><td style="PADDING-BOTTOM: 10px; PADDING-TOP: 10px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; BACKGROUND-COLOR: #616161"><p style="FONT-SIZE: 11px; FONT-FAMILY: Arial, Helvetica, sans-serif; COLOR: #ffffff; LINE-HEIGHT: 18px">© The French language edition of DeviceMed is a publication of Evelyne Gisselbrecht, licensed by Vogel Business Media GmbH &amp; Co. KG, 97082 Wuerzburg/Germany.<br>

© Copyright of the trademark « DeviceMed » by Vogel Business Media GmbH &amp; Co. KG, 97082 Wuerzburg/Germany.<br>

Responsable du contenu rédactionnel sur <a style="text-decoration:none;color:#fff;" href="http://www.devicemed.fr/">www.devicemed.fr</a> : Evelyne Gisselbrecht, éditrice de DeviceMed, 33 rue du Puy-de-Dôme, 63370 Lempdes France</p></td></tr></tbody></table><!----><p></p></td></tr><tr><td style="text-align:center;font-family:Arial;font-size:11px">Le bulletin est adressé à <?php echo $mail; ?></td></tr>

<tr style="font-family:Arial;font-size:11px;color:#005ea8;text-decoration:underline;text-align:center;"><td><a style="text-decoration:none;" href="http://www.devicemed.fr/newsletter/desinscrire/<?php echo $mail; ?>"><span>Se désabonner</span></a></td></tr></tbody></table></td><td width="10" valign="top"></td><td width="160" valign="top"><table style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;"><tbody><tr><td><a href="http://www.device-med.fr/?url=http://www.bgs.eu/&amp;id=21"><img src="http://www.device-med.fr/wp-content/uploads/newsletter/bgs.jpg" width="127px"></a></td></tr></tbody></table></td></tr></tbody></table></div>