<?php
	if(isset($_GET['mail']) && $_GET['mail'] != '') {
		$mail = $_GET['mail'];
	}
?>
<div style="width:850px !important;margin:0 auto;"><table cellspacing="0" cellpadding="0" width="850" border="0" align="center" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin:auto;" id="wrapper"><tbody><tr><td width="700" valign="top" style="background-color:#F1F1F1"><table style="border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt;margin-left:10px;" width="700"><tbody><tr><td><a style="border:none" href="http://www.devicemed.fr/"><img width="700" height="91" title="logo" alt="newsletter" src="http://www.device-med.fr/wp-content/uploads/newsletter/original.jpg"></a></td></tr></tbody></table><table style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;margin-left:10px;margin-top:10px;margin-bottom:10px;" width="700" id="top_news"><tbody><tr><td align="center"><a target="_blank" href="http://www.device-med.fr/?url=http://www.micronora.com&amp;id=51"><img src="http://devicemed.fr/wp-content/uploads/banniere/Mic16-bann_468x60px-FR.gif" border="0" alt="" style="width:468px;text-align:center;"></a></td></tr> </tbody></table>

<table style="border-collapse:collapse;border-top:1px dotted #555;mso-table-lspace:0pt; mso-table-rspace:0pt;margin-left:10px;margin-top:10px;" width="700" id="top_news"><tbody><tr><td align="left"><h1 style="font-size:20px;color:#000000;font-family:Arial;">Sommaire de la newsletter du 24 juin 2015</h1></td></tr> </tbody></table><table width="700" style="border-bottom:0;border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:10px;" id="inhaltsverzeichnis"><tbody><tr><td><ul style="padding-left:20px;margin-top:0px;margin-bottom:0;">

<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/le-cetim-et-le-mica-sassocient-pour-creer-une-plate-forme-dediee-au-dm-implantables/3703" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Cetim&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/le-cetim-et-le-mica-sassocient-pour-creer-une-plate-forme-dediee-au-dm-implantables/3703" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Le Cetim et Mica s’associent pour créer une plate-forme dédiée aux DM implantables</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/une-rentree-du-dispositif-medical-etendue-sur-2-jours-les-17-et-18-septembre-2015/3686" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">ISIFC&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/une-rentree-du-dispositif-medical-etendue-sur-2-jours-les-17-et-18-septembre-2015/3686" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Une «&nbsp;Rentrée du Dispositif Médical&nbsp;» étendue sur 2 jours, les 17 et 18 septembre 2015</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/stiplastics-monte-en-puissance-avec-une-nouvelle-usine-et-des-ambitions-de-dacquisition/3676" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Stiplastics&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/stiplastics-monte-en-puissance-avec-une-nouvelle-usine-et-des-ambitions-de-dacquisition/3676" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Stiplastics monte en puissance avec une nouvelle usine et des ambitions d’acquisition</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/rendez-vous-experts-medtech-avec-trois-societes-de-conseil-le-28-septembre-a-paris/3696" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">DM Experts&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/rendez-vous-experts-medtech-avec-trois-societes-de-conseil-le-28-septembre-a-paris/3696" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Rendez-vous «&nbsp;Experts MedTech&nbsp;», le 28 septembre, avec trois sociétés de conseil</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/alliance-de-competences-en-injection-le-mariage-du-plastique-et-du-silicone/3693" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Plastifrance&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/alliance-de-competences-en-injection-le-mariage-du-plastique-et-du-silicone/3693" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Alliance de compétences en injection : le mariage du plastique et du silicone</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/electriques_electroniques/transpondeurs-nfc-programmables-pour-capteurs-medicaux/3747" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Texas Instruments&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/electriques_electroniques/transpondeurs-nfc-programmables-pour-capteurs-medicaux/3747" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Transpondeurs NFC programmables pour capteurs médicaux</span></a></li><!---->

</ul></td></tr></tbody></table>

<table width="700" style="margin-top:10px;border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:10px;" id="content"><tbody>

<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/le-cetim-et-le-mica-sassocient-pour-creer-une-plate-forme-dediee-au-dm-implantables/3703" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/06/DSCF1371-2-755.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/le-cetim-et-le-mica-sassocient-pour-creer-une-plate-forme-dediee-au-dm-implantables/3703" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Cetim</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/le-cetim-et-le-mica-sassocient-pour-creer-une-plate-forme-dediee-au-dm-implantables/3703" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Le Cetim et Mica s’associent pour créer une plate-forme dédiée aux DM implantables</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">En réunissant leurs compétences et plus de 80 scientifiques pluridisciplinaires, le centre technique Cetim et l’institut de recherche Mica proposent un nouvelle structure nommée IGI-Tech. L’objectif est d’apporter des solutions sur-mesure aux industriels du DM [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/le-cetim-et-le-mica-sassocient-pour-creer-une-plate-forme-dediee-au-dm-implantables/3703" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/evenements/une-rentree-du-dispositif-medical-etendue-sur-2-jours-les-17-et-18-septembre-2015/3686" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/06/rentree-dispositif-medical-2014-8.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/une-rentree-du-dispositif-medical-etendue-sur-2-jours-les-17-et-18-septembre-2015/3686" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">ISIFC</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/une-rentree-du-dispositif-medical-etendue-sur-2-jours-les-17-et-18-septembre-2015/3686" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Une «&nbsp;Rentrée du Dispositif Médical&nbsp;» étendue sur 2 jours, les 17 et 18 septembre 2015</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Forte du succès des deux premières éditions, l’ISIFC renouvelle son événement de formation annuel à Besançon, mais en l’étendant sur 2 journées. La première sera dédiée à l’enregistrement des DM à l’export, et la seconde [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/une-rentree-du-dispositif-medical-etendue-sur-2-jours-les-17-et-18-septembre-2015/3686" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/stiplastics-monte-en-puissance-avec-une-nouvelle-usine-et-des-ambitions-de-dacquisition/3676" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/06/IMG_3161-retouchée.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/stiplastics-monte-en-puissance-avec-une-nouvelle-usine-et-des-ambitions-de-dacquisition/3676" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Stiplastics</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/stiplastics-monte-en-puissance-avec-une-nouvelle-usine-et-des-ambitions-de-dacquisition/3676" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Stiplastics monte en puissance avec une nouvelle usine et des ambitions d’acquisition</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Pour ses 30 ans, la société Stiplastics s’est offert un beau cadeau : une usine flambant neuve de 2300 m2 à St Marcellin (38), inaugurée le 12 juin dernier. De quoi développer son activité de [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/stiplastics-monte-en-puissance-avec-une-nouvelle-usine-et-des-ambitions-de-dacquisition/3676" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/evenements/rendez-vous-experts-medtech-avec-trois-societes-de-conseil-le-28-septembre-a-paris/3696" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/06/DM-Experts-755.png"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/rendez-vous-experts-medtech-avec-trois-societes-de-conseil-le-28-septembre-a-paris/3696" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">DM Experts</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/rendez-vous-experts-medtech-avec-trois-societes-de-conseil-le-28-septembre-a-paris/3696" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Rendez-vous «&nbsp;Experts MedTech&nbsp;», le 28 septembre, avec trois sociétés de conseil</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Trois sociétés de conseil s’associent pour proposer,&nbsp;dans un cadre professionnel et discret, des entretiens individuels&nbsp;aux fabricants de dispositifs médicaux qui rencontrent des problématiques précises. 
Les Rendez-vous Experts MedTech. Tel est le nom de ce nouvel [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/rendez-vous-experts-medtech-avec-trois-societes-de-conseil-le-28-septembre-a-paris/3696" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/alliance-de-competences-en-injection-le-mariage-du-plastique-et-du-silicone/3693" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/06/Plastifrance-755.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/alliance-de-competences-en-injection-le-mariage-du-plastique-et-du-silicone/3693" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Plastifrance</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/alliance-de-competences-en-injection-le-mariage-du-plastique-et-du-silicone/3693" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Alliance de compétences en injection : le mariage du plastique et du silicone</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Plastifrance annonce la signature d’un accord de partenariat avec un injecteur de silicone. L’objectif&nbsp;: pouvoir prendre en charge la conception, la fabrication, l’assemblage et l’industrialisation de projets complets incluant à la fois des composants en [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/alliance-de-competences-en-injection-le-mariage-du-plastique-et-du-silicone/3693" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/composants-oem/electriques_electroniques/transpondeurs-nfc-programmables-pour-capteurs-medicaux/3747" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/06/Texas-Instruments.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/electriques_electroniques/transpondeurs-nfc-programmables-pour-capteurs-medicaux/3747" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Texas Instruments</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/electriques_electroniques/transpondeurs-nfc-programmables-pour-capteurs-medicaux/3747" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Transpondeurs NFC programmables pour capteurs médicaux</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Texas Instruments lance une famille de circuits intégrés de type SoC que l’Américain présente comme les premiers transpondeurs NFC 13,56 MHz programmables à haut niveau d’intégration pour applications industrielles et médicales, dispositifs portés sur soi [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/electriques_electroniques/transpondeurs-nfc-programmables-pour-capteurs-medicaux/3747" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>

</tbody></table><!----><table width="704" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:0px" id="footer"><tbody><tr><td style="font-family:Arial; font-size:12px"><table cellspacing="0" width="702"><tbody><tr><td style="padding-bottom:10px;padding-top:10px;padding-left:10px;padding-right:10px;background-color:#c7c7c7"><table width="700"><tbody><tr><td align="left"><a href="http://news.vogel.de/inxmail2/d?q00wueoq0eqfngbii000000000000000ietwqbri3277"><img src="http://www.devicemed.fr/wp-content/themes/devicemed-responsive/images/newsletter/nl20/vogel_logo.gif" alt="Vogel Logo"></a></td><td align="right"></td></tr></tbody></table></td></tr><!----><tr><td align="center" style="font-size:11px;font-family:Arial,Helvetica,sans-serif;padding:10px;background-color:#d2d2d2;text-align:center;"><a style="text-decoration:none;" href="http://www.devicemed.fr/nous-contacter"><span style="font-size:12px;color:#b30f1d;text-align:center;">Contact</span></a></td></tr><!----><tr><td style="PADDING-BOTTOM: 10px; PADDING-TOP: 10px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; BACKGROUND-COLOR: #616161"><p style="FONT-SIZE: 11px; FONT-FAMILY: Arial, Helvetica, sans-serif; COLOR: #ffffff; LINE-HEIGHT: 18px">© The French language edition of DeviceMed is a publication of Evelyne Gisselbrecht, licensed by Vogel Business Media GmbH &amp; Co. KG, 97082 Wuerzburg/Germany.<br>

© Copyright of the trademark « DeviceMed » by Vogel Business Media GmbH &amp; Co. KG, 97082 Wuerzburg/Germany.<br>

Responsable du contenu rédactionnel sur <a style="text-decoration:none;color:#fff;" href="http://www.devicemed.fr/">www.devicemed.fr</a> : Evelyne Gisselbrecht, éditrice de DeviceMed, 33 rue du Puy-de-Dôme, 63370 Lempdes France</p></td></tr></tbody></table><!----><p></p></td></tr><tr><td style="text-align:center;font-family:Arial;font-size:11px">Le bulletin est adressé à <?php echo $mail; ?></td></tr>

<tr style="font-family:Arial;font-size:11px;color:#005ea8;text-decoration:underline;text-align:center;"><td><a style="text-decoration:none;" href="http://www.devicemed.fr/newsletter/desinscrire/<?php echo $mail; ?>"><span>Se désabonner</span></a></td></tr></tbody></table></td><td width="10" valign="top"></td><td width="160" valign="top"><table style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;"><tbody><tr><td style="padding-bottom:10px;"><a target="_blank" href="http://www.device-med.fr/?url=http://www.devicemed.de/&amp;id=52"><img src="http://www.device-med.fr/wp-content/uploads/newsletter/devicemed_de.jpg" width="127px"></a></td></tr>

<tr><td><div style="width:100%;padding-top:15px;"><a href="http://www.devicemed.fr/suppliers/" target="_blank">

<img width="127px" src="http://www.devicemed.fr/wp-content/uploads/newsletter/repertoirev6.jpg"></a></div></td></tr></tbody></table></td></tr></tbody></table></div>