<?php
	if(isset($_GET['mail']) && $_GET['mail'] != '') {
		$mail = $_GET['mail'];
	}
?>
<div style="width:850px !important;margin:0 auto;"><table cellspacing="0" cellpadding="0" width="850" border="0" align="center" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin:auto;" id="wrapper"><tbody><tr><td width="700" valign="top" style="background-color:#F1F1F1"><table style="border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt;margin-left:10px;" width="700"><tbody><tr><td><a style="border:none" href="http://www.devicemed.fr/"><img width="700" height="91" title="logo" alt="newsletter" src="http://www.device-med.fr/wp-content/uploads/newsletter/original.jpg"></a></td></tr></tbody></table>

<table style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;margin-left:10px;margin-top:10px;" width="700" id="top_news"><tbody><tr><td align="left"><h1 style="font-size:20px;color:#000000;font-family:Arial;">Sommaire de la newsletter du 17 février 2015</h1></td></tr> </tbody></table><table width="700" style="border-bottom:0;border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:10px;" id="inhaltsverzeichnis"><tbody><tr><td><ul style="padding-left:20px;margin-top:0px;margin-bottom:0;"><li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/prochain-medinov-les-8-et-9-avril-2015-a-grenoble/2421" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;">First Connection&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/prochain-medinov-les-8-et-9-avril-2015-a-grenoble/2421" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Prochain MEDI’NOV les 8 et 9 avril 2015 à Grenoble</span></a></li><!---->

<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/electrovanne-miniature-pour-appareils-medicaux-portables/2447" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;">Parker Hannifin&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/electrovanne-miniature-pour-appareils-medicaux-portables/2447" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Electrovanne miniature pour appareils médicaux portables</span></a></li><!---->

<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/une-nouvelle-usine-pour-accompagner-la-croissance-daraymondlife/2438" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;">ARaymondlife&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/une-nouvelle-usine-pour-accompagner-la-croissance-daraymondlife/2438" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Une nouvelle usine pour accompagner la croissance d’ARaymondlife</span></a></li><!---->

<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/ceramiques-et-liaisons-ceramique-metal-biocompatibles-pour-implants/2453" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;">SCT&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/ceramiques-et-liaisons-ceramique-metal-biocompatibles-pour-implants/2453" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Céramiques et liaisons céramique-métal biocompatibles pour implants</span></a></li><!---->

<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/nidays-a-attire-1230-visiteurs-concernes-par-le-test-et-la-mesure/2435" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;">National Instruments France&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/nidays-a-attire-1230-visiteurs-concernes-par-le-test-et-la-mesure/2435" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">NIDays a attiré 1230 visiteurs concernés par le test et la mesure</span></a></li><!---->

<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/julien-roussel-passe-aux-commandes-de-cryla/2443" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;">Cryla&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/julien-roussel-passe-aux-commandes-de-cryla/2443" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Julien Roussel est nommé Directeur Général de Cryla</span></a></li><!---->

</ul></td></tr></tbody></table>

<table width="700" style="margin-top:10px;border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:10px" id="content"><tbody>

<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/prochain-medinov-les-8-et-9-avril-2015-a-grenoble/2421" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/02/First-Connection.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/prochain-medinov-les-8-et-9-avril-2015-a-grenoble/2421" target="_blank"><span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">First Connection</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/prochain-medinov-les-8-et-9-avril-2015-a-grenoble/2421" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Prochain MEDI’NOV les 8 et 9 avril 2015 à Grenoble</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Après Monaco en 2013 et Montpellier en 2014, First Connection a choisi cette année Grenoble, place forte du secteur des technologies médicales, pour organiser la troisième édition de ses rencontres d’affaires MEDI’NOV. En complément de [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/prochain-medinov-les-8-et-9-avril-2015-a-grenoble/2421" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/composants-oem/electrovanne-miniature-pour-appareils-medicaux-portables/2447" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/02/Parker.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/electrovanne-miniature-pour-appareils-medicaux-portables/2447" target="_blank"><span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Parker Hannifin</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/electrovanne-miniature-pour-appareils-medicaux-portables/2447" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Electrovanne miniature pour appareils médicaux portables</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Petite, légère et peu gourmande en énergie, la dernière-née des électrovannes miniatures à clapet de Parker Hannifin est plus particulièrement destinée aux appareils médicaux portables.
Les fabricants d’appareils médicaux portables cherchent naturellement à rallonger la durée [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/electrovanne-miniature-pour-appareils-medicaux-portables/2447" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td colspan="2" style="border-top:1px dotted #555;text-align:center;"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;margin-top:10px;"><span style="font-size:12px;font-family:Helvetica,Arial,sans-serif;color:#999;">Annonce</span></p></td></tr><tr><td colspan="2" width="128" valign="top" style="width:128px;"><div style="padding-bottom: 10px;padding-top: 10px; padding-left: 10px; width: 500px;padding-right: 10px; border: 1px solid #333;margin: 0 auto;margin-bottom: 10px;"><a href="http://www.visioneng.fr/produits/stereomicroscopes" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/newsletter/visions.gif"></a>

<p style="margin:0px;padding-left:140px;"><a style="margin:0px;text-decoration:none;" href="http://www.visioneng.fr/produits/stereomicroscopes" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:black;">Microscopie agréable</span></a></p>

<p style="padding-left:140px;font-size:12px;line-height:21px;font-family:Arial;color:#333;margin:0px;">
								Inspectez et documentez les composants de vos dispositifs médicaux dans une position de travail assise 
								et confortable grâce aux stéréo microscopes sans oculaires et autres systèmes d’inspection optique développés par Vision Engineering. 
								Soulagez votre personnel de la qualité à travers l’utilisation d’outils dont l’ergonomie est maximisée.
								<a style="text-decoration:none;" href="http://www.visioneng.fr/produits/stereomicroscopes" target="_blank"><span style="color:#005ea8;">Pour en savoir plus</span></a></p></div></td></tr>

<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/une-nouvelle-usine-pour-accompagner-la-croissance-daraymondlife/2438" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/02/ARaymond-Life.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/une-nouvelle-usine-pour-accompagner-la-croissance-daraymondlife/2438" target="_blank"><span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">ARaymondlife</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/une-nouvelle-usine-pour-accompagner-la-croissance-daraymondlife/2438" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Une nouvelle usine pour accompagner la croissance d’ARaymondlife</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Entreprise du Réseau ARaymond spécialisée dans l’élaboration de dispositifs médicaux en injection plastique, ARaymondlife a construit une nouvelle usine à Saint-Egrève pour accompagner le développement de son activité santé.
Conformément à la règlementation applicable aux établissements [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/une-nouvelle-usine-pour-accompagner-la-croissance-daraymondlife/2438" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/ceramiques-et-liaisons-ceramique-metal-biocompatibles-pour-implants/2453" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/02/SCT.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/ceramiques-et-liaisons-ceramique-metal-biocompatibles-pour-implants/2453" target="_blank"><span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">SCT</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/ceramiques-et-liaisons-ceramique-metal-biocompatibles-pour-implants/2453" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Céramiques et liaisons céramique-métal biocompatibles pour implants</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Si tant est qu’elles soient biocompatibles, les céramiques techniques représentent une solution de choix pour la fabrication d’implants médicaux. L’entreprise SCT (Société des Céramiques Techniques) s’en est fait une spécialité, avec des céramiques adaptées aux [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/ceramiques-et-liaisons-ceramique-metal-biocompatibles-pour-implants/2453" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/nidays-a-attire-1230-visiteurs-concernes-par-le-test-et-la-mesure/2435" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/02/Jean-Philippe-Baltel.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/nidays-a-attire-1230-visiteurs-concernes-par-le-test-et-la-mesure/2435" target="_blank"><span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">National Instruments France</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/nidays-a-attire-1230-visiteurs-concernes-par-le-test-et-la-mesure/2435" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">NIDays a attiré 1230 visiteurs concernés par le test et la mesure</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Composé d’une exposition et de conférences techniques, NIDays fait chaque année le point sur l’instrumentation virtuelle et la conception graphique de systèmes. Une thématique susceptible d’intéresser toutes les industries, y compris celle du médical.
Organisée par [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/nidays-a-attire-1230-visiteurs-concernes-par-le-test-et-la-mesure/2435" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/julien-roussel-passe-aux-commandes-de-cryla/2443" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/02/Cryla2.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/julien-roussel-passe-aux-commandes-de-cryla/2443" target="_blank"><span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Cryla</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/julien-roussel-passe-aux-commandes-de-cryla/2443" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Julien Roussel est nommé Directeur Général de Cryla</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Concepteur et fabricant de composants microtechniques complexes, Cryla voit sa direction générale confiée à Julien Roussel, qui a occupé de nombreux postes opérationnels, techniques et commerciaux au sein de l’entreprise. M. Roussel succède ainsi à [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/julien-roussel-passe-aux-commandes-de-cryla/2443" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>

</tbody></table><!----><table width="704" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:0px" id="footer"><tbody><tr><td style="font-family:Arial; font-size:12px"><table cellspacing="0" width="702"><tbody><tr><td style="padding-bottom:10px;padding-top:10px;padding-left:10px;padding-right:10px;background-color:#c7c7c7"><table width="700"><tbody><tr><td align="left"><a href="http://news.vogel.de/inxmail2/d?q00wueoq0eqfngbii000000000000000ietwqbri3277"><img src="http://www.devicemed.fr/wp-content/themes/devicemed-responsive/images/newsletter/nl20/vogel_logo.gif" alt="Vogel Logo"></a></td><td align="right"></td></tr></tbody></table></td></tr><!----><tr><td align="center" style="font-size:11px;font-family:Arial,Helvetica,sans-serif;padding:10px;background-color:#d2d2d2;text-align:center;"><a style="text-decoration:none;" href="http://www.devicemed.fr/nous-contacter"><span style="font-size:12px;color:#b30f1d;text-align:center;">Contact</span></a></td></tr><!----><tr><td style="PADDING-BOTTOM: 10px; PADDING-TOP: 10px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; BACKGROUND-COLOR: #616161"><p style="FONT-SIZE: 11px; FONT-FAMILY: Arial, Helvetica, sans-serif; COLOR: #ffffff; LINE-HEIGHT: 18px">© The French language edition of DeviceMed is a publication of Evelyne Gisselbrecht, licensed by Vogel Business Media GmbH &amp; Co. KG, 97082 Wuerzburg/Germany.<br>

© Copyright of the trademark « DeviceMed » by Vogel Business Media GmbH &amp; Co. KG, 97082 Wuerzburg/Germany.<br>

Responsable du contenu rédactionnel sur <a style="text-decoration:none;color:#fff;" href="http://www.devicemed.fr/">www.devicemed.fr</a> : Evelyne Gisselbrecht, éditrice de DeviceMed, 33 rue du Puy-de-Dôme, 63370 Lempdes France</p></td></tr></tbody></table><!----><p></p></td></tr><tr><td style="text-align:center;font-family:Arial;font-size:11px">Le bulletin est adressé à eric423@hotmail.com</td></tr>

<tr style="font-family:Arial;font-size:11px;color:#005ea8;text-decoration:underline;text-align:center;"><td><a style="text-decoration:none;" href="http://www.devicemed.fr/newsletter/desinscrire/eric423@hotmail.com"><span>Se désabonner</span></a></td></tr></tbody></table></td><td width="10" valign="top"></td><td width="160" valign="top"><table style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;"><tbody><tr><td><a href="http://www.devicemed.de/"><img src="http://www.device-med.fr/wp-content/uploads/newsletter/devicemed_de.jpg" width="127px"></a></td></tr></tbody></table></td></tr></tbody></table></div>