<?php
	if(isset($_GET['mail']) && $_GET['mail'] != '') {
		$mail = $_GET['mail'];
	}
?>
<div style="width:850px !important;margin:0 auto;"><table cellspacing="0" cellpadding="0" width="850" border="0" align="center" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin:auto;" id="wrapper"><tbody><tr><td width="700" valign="top" style="background-color:#F1F1F1"><table style="border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt;margin-left:10px;" width="700"><tbody><tr><td><a style="border:none" href="http://www.devicemed.fr/"><img width="700" height="91" title="logo" alt="newsletter" src="http://www.device-med.fr/wp-content/uploads/newsletter/original.jpg"></a></td></tr></tbody></table><table style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;margin-left:10px;margin-top:10px;margin-bottom:10px;" width="700" id="top_news"><tbody><tr><td align="center"><a target="_blank" href="http://www.device-med.fr/?url=http%3A%2F%2Fwww.ni.com%2Fgate%2Fgb%2FGB_SEMINARSLIDES103%2FF%3Fcid%3DAdvertising-701i0000001KXrJAAW-France-none%26metc%3Dmt8pck&amp;id=56"><img src="http://devicemed.fr/wp-content/uploads/banniere/medical_468x60.gif" border="0" alt="" style="width:468px;text-align:center;"></a></td></tr> </tbody></table>

<table style="border-collapse:collapse;border-top:1px dotted #555;mso-table-lspace:0pt; mso-table-rspace:0pt;margin-left:10px;margin-top:10px;" width="700" id="top_news"><tbody><tr><td align="left"><h1 style="font-size:20px;color:#000000;font-family:Arial;">Sommaire de la newsletter du 7 juillet 2015</h1></td></tr> </tbody></table><table width="700" style="border-bottom:0;border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:10px;" id="inhaltsverzeichnis"><tbody><tr><td><ul style="padding-left:20px;margin-top:0px;margin-bottom:0;">

<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/associations_professionnelles/stephane-regnault-reelu-president-du-snitem/3987" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">SNITEM&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/associations_professionnelles/stephane-regnault-reelu-president-du-snitem/3987" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Stéphane Regnault réélu président du syndicat</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/associations_professionnelles/lalsace-labellisee-french-tech-version-medtech/3999" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">La French Tech&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/associations_professionnelles/lalsace-labellisee-french-tech-version-medtech/3999" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">L’Alsace labellisée «&nbsp;French Tech&nbsp;», spécialisée «&nbsp;Medtech&nbsp;»</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/molex-renforce-ses-capacites-de-conception-de-dm-avec-lacquisition-de-protek-medical/4008" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Molex Incorporated&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/molex-renforce-ses-capacites-de-conception-de-dm-avec-lacquisition-de-protek-medical/4008" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Le groupe renforce ses capacités de conception de DM avec l’acquisition de Protek Medical</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/ledition-2015-des-techdays-sante-se-tiendra-a-grenoble-le-29-septembre-prochain/3992" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">I-CARE&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/ledition-2015-des-techdays-sante-se-tiendra-a-grenoble-le-29-septembre-prochain/3992" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">L’édition 2015 des TechDays Santé se tiendra à Grenoble le 29 septembre prochain</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/emballage_conditionnement-sous-traitance-et-services/protections-pour-les-instruments-chirurgicaux-pointus-et-tranchants/4017" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Rose Plastic&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/emballage_conditionnement-sous-traitance-et-services/protections-pour-les-instruments-chirurgicaux-pointus-et-tranchants/4017" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Protections pour les instruments chirurgicaux pointus et tranchants</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/maitriser-toutes-les-techniques-de-plasturgie-cest-possible/3968" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Fimado&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/maitriser-toutes-les-techniques-de-plasturgie-cest-possible/3968" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Maîtriser toutes les techniques de plasturgie : c’est possible !</span></a></li><!---->

</ul></td></tr></tbody></table>

<table width="700" style="margin-top:10px;border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:10px;" id="content"><tbody>

<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/associations_professionnelles/stephane-regnault-reelu-president-du-snitem/3987" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2013/07/599603-e1436167959949.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/associations_professionnelles/stephane-regnault-reelu-president-du-snitem/3987" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">SNITEM</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/associations_professionnelles/stephane-regnault-reelu-president-du-snitem/3987" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Stéphane Regnault réélu président du syndicat</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Les adhérents du Syndicat National de l’Industrie des Technologies Médicales (SNITEM), réunis à l’occasion de leur Assemblée Générale annuelle, ont réélu Stéphane Regnault pour un mandat de deux ans à la présidence de l’organisation professionnelle. [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/associations_professionnelles/stephane-regnault-reelu-president-du-snitem/3987" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/associations_professionnelles/lalsace-labellisee-french-tech-version-medtech/3999" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/07/Mission-French-Tech.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/associations_professionnelles/lalsace-labellisee-french-tech-version-medtech/3999" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">La French Tech</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/associations_professionnelles/lalsace-labellisee-french-tech-version-medtech/3999" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">L’Alsace labellisée «&nbsp;French Tech&nbsp;», spécialisée «&nbsp;Medtech&nbsp;»</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Dans le cadre de son programme de labellisation de «&nbsp;Métropoles French Tech&nbsp;», l’Etat vient d’annoncer 8 nouveaux écosystèmes remarquables, susceptibles de soutenir les start-up et l’innovation made in France. Quatre d’entre eux bénéficient d’un label [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/associations_professionnelles/lalsace-labellisee-french-tech-version-medtech/3999" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td colspan="2" style="border-top:1px dotted #555;padding-left:90px;"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;margin-top:10px;"><span style="font-size:12px;font-family:Helvetica,Arial,sans-serif;color:#999;">Annonce</span></p></td></tr><tr><td colspan="2" width="128" valign="top" style="width:128px;padding-bottom: 10px;padding-left:90px;">

<div style="padding:10px;width:500px;border:1px solid #333;">

<a href="http://www.device-med.fr/?url=http%3A%2F%2Fp.protolabs.fr%2Fmedical-white-paper%3Futm_campaign%3Dfr-sos%26utm_medium%3Demail%26utm_source%3Ddevicemed%26utm_content%3Den-medwp-0715&amp;id=57" target="_blank">

<img style="border:solid 1px #FFFFFF;padding-right:10px;" width="100" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/banniere/medical-prototyping.jpg">

</a>

<p style="margin:0px;padding-left:140px;"><a style="margin:0px;text-decoration:none;" href="http://www.device-med.fr/?url=http%3A%2F%2Fp.protolabs.fr%2Fmedical-white-paper%3Futm_campaign%3Dfr-sos%26utm_medium%3Demail%26utm_source%3Ddevicemed%26utm_content%3Den-medwp-0715&amp;id=57" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:black;">Le prototypage pour le secteur médical</span></a></p>

<p style="padding-left:140px;font-size:12px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Ce livre blanc examine les diverses options de fabrication rapide à la disposition des ingénieurs-concepteurs et 

développeurs de produits du secteur médical. Analysez points forts et points faibles de chaque processus, facilitant les choix de matériaux adaptés pour votre application.<a style="text-decoration:none;" href="http://www.device-med.fr/?url=http%3A%2F%2Fp.protolabs.fr%2Fmedical-white-paper%3Futm_campaign%3Dfr-sos%26utm_medium%3Demail%26utm_source%3Ddevicemed%26utm_content%3Den-medwp-0715&amp;id=57" target="_blank">Télécharger</a>.

</p></div></td></tr>

<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/molex-renforce-ses-capacites-de-conception-de-dm-avec-lacquisition-de-protek-medical/4008" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/07/Protek-Medical.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/molex-renforce-ses-capacites-de-conception-de-dm-avec-lacquisition-de-protek-medical/4008" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Molex Incorporated</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/molex-renforce-ses-capacites-de-conception-de-dm-avec-lacquisition-de-protek-medical/4008" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Le groupe renforce ses capacités de conception de DM avec l’acquisition de Protek Medical</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Parmi les leaders des solutions d’interconnexion, Molex vient d’annoncer l’acquisition de l’Irlandais Protek Medical, une société d’ingénierie et de fabrication en sous-traitance d’équipements médicaux. Celle-ci apporte ses compétences en matière d’injection plastique, d’assemblage en salle [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/molex-renforce-ses-capacites-de-conception-de-dm-avec-lacquisition-de-protek-medical/4008" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/evenements/ledition-2015-des-techdays-sante-se-tiendra-a-grenoble-le-29-septembre-prochain/3992" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/07/i-care-cluster.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/ledition-2015-des-techdays-sante-se-tiendra-a-grenoble-le-29-septembre-prochain/3992" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">I-CARE</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/ledition-2015-des-techdays-sante-se-tiendra-a-grenoble-le-29-septembre-prochain/3992" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">L’édition 2015 des TechDays Santé se tiendra à Grenoble le 29 septembre prochain</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Entre congrès médicaux et salons industriels, les TechDays Santé réunissent chaque année les acteurs des technologies de santé, des concepteurs de DM et leurs sous-traitants, aux professionnels de santé et chercheurs. A travers ce positionnement [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/ledition-2015-des-techdays-sante-se-tiendra-a-grenoble-le-29-septembre-prochain/3992" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/emballage_conditionnement-sous-traitance-et-services/protections-pour-les-instruments-chirurgicaux-pointus-et-tranchants/4017" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/07/Rose-Plastics-2.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/emballage_conditionnement-sous-traitance-et-services/protections-pour-les-instruments-chirurgicaux-pointus-et-tranchants/4017" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Rose Plastic</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/emballage_conditionnement-sous-traitance-et-services/protections-pour-les-instruments-chirurgicaux-pointus-et-tranchants/4017" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Protections pour les instruments chirurgicaux pointus et tranchants</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Avec les gammes Tip cover et Quadropack Tip line, la société allemande Rose Plastic Medical Packaging a développé deux emballages offrant une protection optimale pour les pointes fragiles et les arêtes tranchantes des instruments chirurgicaux.
La [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/emballage_conditionnement-sous-traitance-et-services/protections-pour-les-instruments-chirurgicaux-pointus-et-tranchants/4017" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/maitriser-toutes-les-techniques-de-plasturgie-cest-possible/3968" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/07/Manudo-755.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/maitriser-toutes-les-techniques-de-plasturgie-cest-possible/3968" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Fimado</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/maitriser-toutes-les-techniques-de-plasturgie-cest-possible/3968" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Maîtriser toutes les techniques de plasturgie : c’est possible !</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Comme ils en avaient confié le souhait à DeviceMed dès janvier 2013, les dirigeants du groupe Fimado élargissent leur offre de sous-traitance en plasturgie à une nouvelle technologie et non des moindres : l’injection plastique. [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/maitriser-toutes-les-techniques-de-plasturgie-cest-possible/3968" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>

</tbody></table><!----><table width="704" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:0px" id="footer"><tbody><tr><td style="font-family:Arial; font-size:12px"><table cellspacing="0" width="702"><tbody><tr><td style="padding-bottom:10px;padding-top:10px;padding-left:10px;padding-right:10px;background-color:#c7c7c7"><table width="700"><tbody><tr><td align="left"><a href="http://news.vogel.de/inxmail2/d?q00wueoq0eqfngbii000000000000000ietwqbri3277"><img src="http://www.devicemed.fr/wp-content/themes/devicemed-responsive/images/newsletter/nl20/vogel_logo.gif" alt="Vogel Logo"></a></td><td align="right"></td></tr></tbody></table></td></tr><!----><tr><td align="center" style="font-size:11px;font-family:Arial,Helvetica,sans-serif;padding:10px;background-color:#d2d2d2;text-align:center;"><a style="text-decoration:none;" href="http://www.devicemed.fr/nous-contacter"><span style="font-size:12px;color:#b30f1d;text-align:center;">Contact</span></a></td></tr><!----><tr><td style="PADDING-BOTTOM: 10px; PADDING-TOP: 10px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; BACKGROUND-COLOR: #616161"><p style="FONT-SIZE: 11px; FONT-FAMILY: Arial, Helvetica, sans-serif; COLOR: #ffffff; LINE-HEIGHT: 18px">© The French language edition of DeviceMed is a publication of Evelyne Gisselbrecht, licensed by Vogel Business Media GmbH &amp; Co. KG, 97082 Wuerzburg/Germany.<br>

© Copyright of the trademark « DeviceMed » by Vogel Business Media GmbH &amp; Co. KG, 97082 Wuerzburg/Germany.<br>

Responsable du contenu rédactionnel sur <a style="text-decoration:none;color:#fff;" href="http://www.devicemed.fr/">www.devicemed.fr</a> : Evelyne Gisselbrecht, éditrice de DeviceMed, 33 rue du Puy-de-Dôme, 63370 Lempdes France</p></td></tr></tbody></table><!----><p></p></td></tr><tr><td style="text-align:center;font-family:Arial;font-size:11px">Le bulletin est adressé à <?php echo $mail; ?></td></tr>

<tr style="font-family:Arial;font-size:11px;color:#005ea8;text-decoration:underline;text-align:center;"><td><a style="text-decoration:none;" href="http://www.devicemed.fr/newsletter/desinscrire/<?php echo $mail; ?>"><span>Se désabonner</span></a></td></tr></tbody></table></td><td width="10" valign="top"></td><td width="160" valign="top"><table style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;"><tbody><tr><td style="padding-bottom:10px;"><a target="_blank" href="http://www.device-med.fr/?url=http://www.devicemed.de/&amp;id=58"><img src="http://www.device-med.fr/wp-content/uploads/newsletter/devicemed_de.jpg" width="127px"></a></td></tr>

<tr><td><div style="width:100%;padding-top:15px;"><a href="http://devicemed.fr/wp-content/uploads/archives/pdf/guide_acheteur2015.pdf" target="_blank">

<img width="127px" src="http://devicemed.fr/wp-content/uploads/banniere/pave_guide.jpg"></a></div></td></tr></tbody></table></td></tr></tbody></table></div>