<?php
	if(isset($_GET['mail']) && $_GET['mail'] != '') {
		$mail = $_GET['mail'];
	}
?>
<div style="width:850px !important;margin:0 auto;"><table cellspacing="0" cellpadding="0" width="850" border="0" align="center" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin:auto;" id="wrapper"><tbody><tr><td width="700" valign="top" style="background-color:#F1F1F1"><table style="border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt;margin-left:10px;" width="700"><tbody><tr><td><a style="border:none" href="http://www.devicemed.fr/"><img width="700" height="91" title="logo" alt="newsletter" src="http://www.device-med.fr/wp-content/uploads/newsletter/original.jpg"></a></td></tr></tbody></table><table style="border-collapse:collapse;mso-table-lspace:0pt; mso-table-rspace:0pt;margin-left:10px;margin-top:10px;" width="700" id="top_news"><tbody><tr><td align="left"><h1 style="font-size:20px;color:#000000;font-family:Arial;">Sommaire de la newsletter du 22 juillet 2015</h1></td></tr> </tbody></table><table width="700" style="border-bottom:0;border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:10px;" id="inhaltsverzeichnis"><tbody><tr><td><ul style="padding-left:20px;margin-top:0px;margin-bottom:0;">

<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/tubes/un-implant-ultra-fin-pour-acheminer-medicament-et-lumiere-au-sein-du-cerveau/4084" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">NIH&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/tubes/un-implant-ultra-fin-pour-acheminer-medicament-et-lumiere-au-sein-du-cerveau/4084" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Un implant ultra-fin pour acheminer médicament et lumière au sein du cerveau</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/bgs-construit-une-nouvelle-usine-de-traitement-par-rayonnement-gamma/4072" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Beta Gamma Service GmbH&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/bgs-construit-une-nouvelle-usine-de-traitement-par-rayonnement-gamma/4072" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">BGS construit une nouvelle usine de traitement par rayonnement gamma</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/forums-lne-sur-la-reglementation-dediee-aux-dm-et-dm-div-a-paris-et-a-lyon-en-septembre-2015/4060" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">LNE&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/forums-lne-sur-la-reglementation-dediee-aux-dm-et-dm-div-a-paris-et-a-lyon-en-septembre-2015/4060" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Forums sur la réglementation dédiée aux DM et DMDIV, à Paris et à Lyon en septembre 2015</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/systemes-embarques-et-internet-des-objets-a-lhonneur-sur-enova-paris-2015/4056" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">GL Events&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/systemes-embarques-et-internet-des-objets-a-lhonneur-sur-enova-paris-2015/4056" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Systèmes embarqués et Internet des Objets à l’honneur sur ENOVA Paris 2015</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/analyse-dimages-et-mesure-de-pression-pour-dm-dinjection/4105" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">National Instruments&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/analyse-dimages-et-mesure-de-pression-pour-dm-dinjection/4105" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Analyse d’images et mesure de pression pour DM d’injection</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/materiaux/ceramiques/composants-en-ceramique-piezoelectrique-pour-la-pulverisation-de-medicaments/4121" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">PI France&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/materiaux/ceramiques/composants-en-ceramique-piezoelectrique-pour-la-pulverisation-de-medicaments/4121" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Composants en céramique piézoélectrique pour la pulvérisation de médicaments</span></a></li><!---->

</ul></td></tr></tbody></table>

<table width="700" style="margin-top:10px;border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:10px;" id="content"><tbody>

<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/composants-oem/tubes/un-implant-ultra-fin-pour-acheminer-medicament-et-lumiere-au-sein-du-cerveau/4084" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/07/élargie.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/tubes/un-implant-ultra-fin-pour-acheminer-medicament-et-lumiere-au-sein-du-cerveau/4084" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">NIH</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/tubes/un-implant-ultra-fin-pour-acheminer-medicament-et-lumiere-au-sein-du-cerveau/4084" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Un implant ultra-fin pour acheminer médicament et lumière au sein du cerveau</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Des chercheurs américains ont développé un implant cérébral révolutionnaire, capable d’être activé sans fil, pour délivrer des médicaments et de la lumière dans le cerveau, et ce sans dommage neuronal.

L’optogénétique est une discipline scientifique relativement [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/tubes/un-implant-ultra-fin-pour-acheminer-medicament-et-lumiere-au-sein-du-cerveau/4084" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/bgs-construit-une-nouvelle-usine-de-traitement-par-rayonnement-gamma/4072" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/07/BGS-2-755.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/bgs-construit-une-nouvelle-usine-de-traitement-par-rayonnement-gamma/4072" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Beta Gamma Service GmbH</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/bgs-construit-une-nouvelle-usine-de-traitement-par-rayonnement-gamma/4072" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">BGS construit une nouvelle usine de traitement par rayonnement gamma</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Spécialiste de la stérilisation et de la réticulation par rayonnements, la société allemande BGS investit près de 14 millions d’euros dans la construction d’une nouvelle usine près de Karlsruhe. Ce nouveau site accueillera une installation [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/bgs-construit-une-nouvelle-usine-de-traitement-par-rayonnement-gamma/4072" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/evenements/forums-lne-sur-la-reglementation-dediee-aux-dm-et-dm-div-a-paris-et-a-lyon-en-septembre-2015/4060" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/07/LNE.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/forums-lne-sur-la-reglementation-dediee-aux-dm-et-dm-div-a-paris-et-a-lyon-en-septembre-2015/4060" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">LNE</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/forums-lne-sur-la-reglementation-dediee-aux-dm-et-dm-div-a-paris-et-a-lyon-en-septembre-2015/4060" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Forums sur la réglementation dédiée aux DM et DMDIV, à Paris et à Lyon en septembre 2015</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Le LNE organise tout au long de l’année des événements pour faire le point sur les dernières évolutions de la normalisation et de la réglementation. En réponse aux besoins spécifiques des dispositifs médicaux, le laboratoire [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/forums-lne-sur-la-reglementation-dediee-aux-dm-et-dm-div-a-paris-et-a-lyon-en-septembre-2015/4060" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/evenements/systemes-embarques-et-internet-des-objets-a-lhonneur-sur-enova-paris-2015/4056" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/07/GL-Events-755.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/systemes-embarques-et-internet-des-objets-a-lhonneur-sur-enova-paris-2015/4056" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">GL Events</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/systemes-embarques-et-internet-des-objets-a-lhonneur-sur-enova-paris-2015/4056" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Systèmes embarqués et Internet des Objets à l’honneur sur ENOVA Paris 2015</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Après son édition à Toulouse en mars dernier, le salon ENOVA se tiendra à Paris Porte de Versailles du 22 au 24 septembre prochains. Ce rendez-vous annuel des spécialistes de l’électronique, de la mesure, de [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/systemes-embarques-et-internet-des-objets-a-lhonneur-sur-enova-paris-2015/4056" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/analyse-dimages-et-mesure-de-pression-pour-dm-dinjection/4105" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/07/National-Instruments-755.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/analyse-dimages-et-mesure-de-pression-pour-dm-dinjection/4105" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">National Instruments</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/analyse-dimages-et-mesure-de-pression-pour-dm-dinjection/4105" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Analyse d’images et mesure de pression pour DM d’injection</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Pour développer son dispositif d’injection sans aiguille ZENEO, la start-up française Crossject a dû mettre en place une chaine d’acquisition associant une caméra vidéo rapide et une instrumentation de pression dynamique. Elle a fait appel [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/analyse-dimages-et-mesure-de-pression-pour-dm-dinjection/4105" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/materiaux/ceramiques/composants-en-ceramique-piezoelectrique-pour-la-pulverisation-de-medicaments/4121" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/07/PI-France.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/materiaux/ceramiques/composants-en-ceramique-piezoelectrique-pour-la-pulverisation-de-medicaments/4121" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">PI France</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/materiaux/ceramiques/composants-en-ceramique-piezoelectrique-pour-la-pulverisation-de-medicaments/4121" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Composants en céramique piézoélectrique pour la pulvérisation de médicaments</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Fabriqués dans des formats très variés, les composants piézoélectriques offrent des solutions sur mesure pour diverses applications, comme le broyage de calculs rénaux, l’élimination de la plaque dentaire ou la production d’aérosols pour la thérapie [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/materiaux/ceramiques/composants-en-ceramique-piezoelectrique-pour-la-pulverisation-de-medicaments/4121" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>

</tbody></table><!----><table width="704" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:0px" id="footer"><tbody><tr><td style="font-family:Arial; font-size:12px"><table cellspacing="0" width="702"><tbody><tr><td style="padding-bottom:10px;padding-top:10px;padding-left:10px;padding-right:10px;background-color:#c7c7c7"><table width="700"><tbody><tr><td align="left"><a href="http://news.vogel.de/inxmail2/d?q00wueoq0eqfngbii000000000000000ietwqbri3277"><img src="http://www.devicemed.fr/wp-content/themes/devicemed-responsive/images/newsletter/nl20/vogel_logo.gif" alt="Vogel Logo"></a></td><td align="right"></td></tr></tbody></table></td></tr><!----><tr><td align="center" style="font-size:11px;font-family:Arial,Helvetica,sans-serif;padding:10px;background-color:#d2d2d2;text-align:center;"><a style="text-decoration:none;" href="http://www.devicemed.fr/nous-contacter"><span style="font-size:12px;color:#b30f1d;text-align:center;">Contact</span></a></td></tr><!----><tr><td style="PADDING-BOTTOM: 10px; PADDING-TOP: 10px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; BACKGROUND-COLOR: #616161"><p style="FONT-SIZE: 11px; FONT-FAMILY: Arial, Helvetica, sans-serif; COLOR: #ffffff; LINE-HEIGHT: 18px">© The French language edition of DeviceMed is a publication of Evelyne Gisselbrecht, licensed by Vogel Business Media GmbH &amp; Co. KG, 97082 Wuerzburg/Germany.<br>

© Copyright of the trademark « DeviceMed » by Vogel Business Media GmbH &amp; Co. KG, 97082 Wuerzburg/Germany.<br>

Responsable du contenu rédactionnel sur <a style="text-decoration:none;color:#fff;" href="http://www.devicemed.fr/">www.devicemed.fr</a> : Evelyne Gisselbrecht, éditrice de DeviceMed, 33 rue du Puy-de-Dôme, 63370 Lempdes France</p></td></tr></tbody></table><!----><p></p></td></tr><tr><td style="text-align:center;font-family:Arial;font-size:11px">Le bulletin est adressé à <?php echo $mail; ?></td></tr>

<tr style="font-family:Arial;font-size:11px;color:#005ea8;text-decoration:underline;text-align:center;"><td><a style="text-decoration:none;" href="http://www.devicemed.fr/newsletter/desinscrire/<?php echo $mail; ?>"><span>Se désabonner</span></a></td></tr></tbody></table></td><td width="10" valign="top"></td><td width="160" valign="top"><table style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;"><tbody><tr><td style="padding-bottom:10px;"><a target="_blank" href="http://www.device-med.fr/?url=http://www.devicemed.de/&amp;id=60"><img src="http://www.device-med.fr/wp-content/uploads/newsletter/devicemed_de.jpg" width="127px"></a></td></tr>

<tr><td><div style="width:100%;padding-top:15px;"><a href="http://www.devicemed.fr/wp-content/uploads/archives/pdf/guide_acheteur2015.pdf" target="_blank">

<img width="127px" src="http://devicemed.fr/wp-content/uploads/banniere/pave_guide.jpg"></a></div></td></tr></tbody></table></td></tr></tbody></table></div>