<?php
	if(isset($_GET['mail']) && $_GET['mail'] != '') {
		$mail = $_GET['mail'];
	}
?>
<div style="width:850px !important;margin:0 auto;"><table cellspacing="0" cellpadding="0" width="850" border="0" align="center" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin:auto;" id="wrapper"><tbody><tr><td width="700" valign="top" style="background-color:#F1F1F1"><table style="border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt;margin-left:10px;" width="700"><tbody><tr><td><a style="border:none" href="http://www.devicemed.fr/"><img width="700" height="91" title="logo" alt="newsletter" src="http://www.device-med.fr/wp-content/uploads/newsletter/original.jpg"></a></td></tr></tbody></table><table style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;margin-left:10px;margin-top:10px;margin-bottom:10px;" width="700" id="top_news"><tbody><tr><td align="center"><a target="_blank" href="http://www.device-med.fr/?url=http://www.iconnect-exhibition.com&amp;id=23"><img src="http://devicemed.fr/wp-content/uploads/newsletter/iconnect_fr.jpg" border="0" alt="" style="margin-top:5px;width:468px;text-align:center;"></a></td></tr> </tbody></table>

<table style="border-collapse:collapse;border-top:1px dotted #555;mso-table-lspace:0pt; mso-table-rspace:0pt;margin-left:10px;margin-top:10px;" width="700" id="top_news"><tbody><tr><td align="left" style="padding-top:10px;"><h1 style="font-size:20px;color:#000000;font-family:Arial;">Sommaire de la newsletter du 1<sup>er</sup> avril 2015</h1></td></tr> </tbody></table><table width="700" style="border-bottom:0;border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:10px;" id="inhaltsverzeichnis"><tbody><tr><td><ul style="padding-left:20px;margin-top:0px;margin-bottom:0;">

<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/psb-industries-acquiert-plastibell-et-cree-un-pole-sante-industrie/2767" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">PSB Industries&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/psb-industries-acquiert-plastibell-et-cree-un-pole-sante-industrie/2767" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">PSB Industries acquiert Plastibell et crée un pôle Santé &amp; Industrie</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/travail_metaux/ebavurage-de-pieces-complexes-par-centrifugeuse-magnetique/2750" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">ABC SwissTech&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/travail_metaux/ebavurage-de-pieces-complexes-par-centrifugeuse-magnetique/2750" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Ebavurage de pièces complexes par centrifugeuse magnétique</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/enjeux-et-challenges-pour-lorthopedie-de-demain-les-18-et-19-mai-2015-a-marseille/2779" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">CARMA&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/enjeux-et-challenges-pour-lorthopedie-de-demain-les-18-et-19-mai-2015-a-marseille/2779" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Enjeux et challenges pour l’orthopédie de demain, les 18 et 19 mai 2015 à Marseille</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/materiaux/materiaux-plastiques/resine-polyphenylsulfone-autoclavable-pour-les-instruments-de-diagnostic-in-vitro/2797" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Solvay&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/materiaux/materiaux-plastiques/resine-polyphenylsulfone-autoclavable-pour-les-instruments-de-diagnostic-in-vitro/2797" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Résine polyphénylsulfone autoclavable pour les instruments de diagnostic in vitro</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/mecaniques/connecteur-personnalise-non-magnetique-et-a-verrouillage-rapide/2791" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Groupe ODU&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/mecaniques/connecteur-personnalise-non-magnetique-et-a-verrouillage-rapide/2791" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Connecteur personnalisé non-magnétique et à verrouillage rapide</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/accessoires-in-vitro/raccords-filetes-pour-equipements-de-diagnostic/2803" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Diba Industries&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/accessoires-in-vitro/raccords-filetes-pour-equipements-de-diagnostic/2803" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Raccords filetés pour équipements de diagnostic</span></a></li><!---->

</ul></td></tr></tbody></table>

<table width="700" style="margin-top:10px;border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:10px" id="content"><tbody>

<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/psb-industries-acquiert-plastibell-et-cree-un-pole-sante-industrie/2767" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/03/PSB-Industries.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/psb-industries-acquiert-plastibell-et-cree-un-pole-sante-industrie/2767" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">PSB Industries</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/psb-industries-acquiert-plastibell-et-cree-un-pole-sante-industrie/2767" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">PSB Industries acquiert Plastibell et crée un pôle Santé &amp; Industrie</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Acteur international reconnu dans l’injection plastique pour le marché de la santé notamment, Plastibell passe aux mains de PSB Industries, qui crée par la même occasion un nouveau pôle «&nbsp;Santé &amp; Industrie&nbsp;» pesant 100 M€.
Avec [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/psb-industries-acquiert-plastibell-et-cree-un-pole-sante-industrie/2767" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/travail_metaux/ebavurage-de-pieces-complexes-par-centrifugeuse-magnetique/2750" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/03/ABC-SwissTech.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/travail_metaux/ebavurage-de-pieces-complexes-par-centrifugeuse-magnetique/2750" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">ABC SwissTech</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/travail_metaux/ebavurage-de-pieces-complexes-par-centrifugeuse-magnetique/2750" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Ebavurage de pièces complexes par centrifugeuse magnétique</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Nominé aux Trophées de l’Innovation d’Industrie Lyon 2015, le nouveau procédé de tribofinition développé par ABC SwissTech permet de traiter des pièces présentant des zones difficiles d’accès. Ce procédé fait appel au brassage magnétique de [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/travail_metaux/ebavurage-de-pieces-complexes-par-centrifugeuse-magnetique/2750" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/evenements/enjeux-et-challenges-pour-lorthopedie-de-demain-les-18-et-19-mai-2015-a-marseille/2779" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/03/Carma.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/enjeux-et-challenges-pour-lorthopedie-de-demain-les-18-et-19-mai-2015-a-marseille/2779" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">CARMA</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/enjeux-et-challenges-pour-lorthopedie-de-demain-les-18-et-19-mai-2015-a-marseille/2779" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Enjeux et challenges pour l’orthopédie de demain, les 18 et 19 mai 2015 à Marseille</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Le CARMA articulera la 4ème édition de ses Rencontres Régionales Recherche-Industrie-Clinique en Biomécanique Ostéoarticulaire sur les thèmes de l’ingénierie tissulaire et des procédés de fonctionnalisation des surfaces.

Le Centre d’Animation Régional en Matériaux Avancés (CARMA) développe [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/enjeux-et-challenges-pour-lorthopedie-de-demain-les-18-et-19-mai-2015-a-marseille/2779" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/materiaux/materiaux-plastiques/resine-polyphenylsulfone-autoclavable-pour-les-instruments-de-diagnostic-in-vitro/2797" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/03/Solvay.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/materiaux/materiaux-plastiques/resine-polyphenylsulfone-autoclavable-pour-les-instruments-de-diagnostic-in-vitro/2797" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Solvay</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/materiaux/materiaux-plastiques/resine-polyphenylsulfone-autoclavable-pour-les-instruments-de-diagnostic-in-vitro/2797" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Résine polyphénylsulfone autoclavable pour les instruments de diagnostic in vitro</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Thermoplastique aux propriétés exceptionnelles, le PPSU Radel de Solvay a été choisi par ELITechGroup Biomedical Systems pour le moulage par injection de carrousels destinés à ses nouveaux colorateurs de lames. Cette résine se distingue par [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/materiaux/materiaux-plastiques/resine-polyphenylsulfone-autoclavable-pour-les-instruments-de-diagnostic-in-vitro/2797" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/composants-oem/mecaniques/connecteur-personnalise-non-magnetique-et-a-verrouillage-rapide/2791" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/03/Groupe-ODU.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/mecaniques/connecteur-personnalise-non-magnetique-et-a-verrouillage-rapide/2791" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Groupe ODU</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/mecaniques/connecteur-personnalise-non-magnetique-et-a-verrouillage-rapide/2791" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Connecteur personnalisé non-magnétique et à verrouillage rapide</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">

Utilisée dans le domaine médical pour sa fiabilité éprouvée, la solution de connexion ODU-MAC troque sa structure métallique pour une enceinte en plastique et un système de verrouillage rapide. Elle élargit ainsi son spectre d’applications [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/mecaniques/connecteur-personnalise-non-magnetique-et-a-verrouillage-rapide/2791" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/composants-oem/accessoires-in-vitro/raccords-filetes-pour-equipements-de-diagnostic/2803" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/03/Diba.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/accessoires-in-vitro/raccords-filetes-pour-equipements-de-diagnostic/2803" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Diba Industries</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/accessoires-in-vitro/raccords-filetes-pour-equipements-de-diagnostic/2803" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Raccords filetés pour équipements de diagnostic</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Spécialiste de la transmission de fluides pour le médical, Diba Industries étoffe sa gamme de raccords avec deux nouveaux modèles basés sur sa technologie Click-N-Seal. Celle-ci permet de garantir une étanchéité fiable sans recours à [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/accessoires-in-vitro/raccords-filetes-pour-equipements-de-diagnostic/2803" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>

</tbody></table><!----><table width="704" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:0px" id="footer"><tbody><tr><td style="font-family:Arial; font-size:12px"><table cellspacing="0" width="702"><tbody><tr><td style="padding-bottom:10px;padding-top:10px;padding-left:10px;padding-right:10px;background-color:#c7c7c7"><table width="700"><tbody><tr><td align="left"><a href="http://news.vogel.de/inxmail2/d?q00wueoq0eqfngbii000000000000000ietwqbri3277"><img src="http://www.devicemed.fr/wp-content/themes/devicemed-responsive/images/newsletter/nl20/vogel_logo.gif" alt="Vogel Logo"></a></td><td align="right"></td></tr></tbody></table></td></tr><!----><tr><td align="center" style="font-size:11px;font-family:Arial,Helvetica,sans-serif;padding:10px;background-color:#d2d2d2;text-align:center;"><a style="text-decoration:none;" href="http://www.devicemed.fr/nous-contacter"><span style="font-size:12px;color:#b30f1d;text-align:center;">Contact</span></a></td></tr><!----><tr><td style="PADDING-BOTTOM: 10px; PADDING-TOP: 10px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; BACKGROUND-COLOR: #616161"><p style="FONT-SIZE: 11px; FONT-FAMILY: Arial, Helvetica, sans-serif; COLOR: #ffffff; LINE-HEIGHT: 18px">© The French language edition of DeviceMed is a publication of Evelyne Gisselbrecht, licensed by Vogel Business Media GmbH &amp; Co. KG, 97082 Wuerzburg/Germany.<br>

© Copyright of the trademark « DeviceMed » by Vogel Business Media GmbH &amp; Co. KG, 97082 Wuerzburg/Germany.<br>

Responsable du contenu rédactionnel sur <a style="text-decoration:none;color:#fff;" href="http://www.devicemed.fr/">www.devicemed.fr</a> : Evelyne Gisselbrecht, éditrice de DeviceMed, 33 rue du Puy-de-Dôme, 63370 Lempdes France</p></td></tr></tbody></table><!----><p></p></td></tr><tr><td style="text-align:center;font-family:Arial;font-size:11px">Le bulletin est adressé à <?php echo $mail; ?></td></tr>

<tr style="font-family:Arial;font-size:11px;color:#005ea8;text-decoration:underline;text-align:center;"><td><a style="text-decoration:none;" href="http://www.devicemed.fr/newsletter/desinscrire/<?php echo $mail; ?>"><span>Se désabonner</span></a></td></tr></tbody></table></td><td width="10" valign="top"></td><td width="160" valign="top"><table style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;"><tbody><tr><td style="padding-bottom:10px;"><a target="_blank" href="http://www.device-med.fr/?url=http://www.bgs.eu/homepage.html?&amp;no_cache=1&amp;L=2&amp;no_cache=1&amp;id=24"><img src="http://www.device-med.fr/wp-content/uploads/newsletter/bgs.jpg" width="127px"></a></td></tr>

<tr><td><div style="width:100%;padding-top:10px;"><a href="http://www.devicemed.fr/wp-content/uploads/archives/pdf/mars_avril2015.pdf" target="_blank">

<img width="127px" src="http://www.devicemed.fr/wp-content/uploads/archives/apercu/mars_avril2015_nl.png"></a></div>

<div style="color:#3336ff;text-transform:uppercase;font-size: 12px;font-weight: bold;font-family: Helvetica,Arial,sans-serif;color: #005ea8;width: 100%;padding-top:5px;text-align:center;">Découvrez notre dernier numéro</div></td></tr>

</tbody></table></td></tr></tbody></table></div>