<?php
	if(isset($_GET['mail']) && $_GET['mail'] != '') {
		$mail = $_GET['mail'];
	}
?>
<div style="width:850px !important;margin:0 auto;"><table cellspacing="0" cellpadding="0" width="850" border="0" align="center" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin:auto;" id="wrapper"><tbody><tr><td width="700" valign="top" style="background-color:#F1F1F1"><table style="border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt;margin-left:10px;" width="700"><tbody><tr><td><a style="border:none" href="http://www.devicemed.fr/"><img width="700" height="91" title="logo" alt="newsletter" src="http://www.device-med.fr/wp-content/uploads/newsletter/original.jpg"></a></td></tr></tbody></table><table style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;margin-left:10px;margin-top:10px;margin-bottom:10px;" width="700" id="top_news"><tbody><tr><td align="center"><a target="_blank" href="http://www.device-med.fr/?url=http://medteceurope.com/fr/france?cid=MTFR_ban_vis_120515_devicemed_newsletter_fullsize_static&amp;id=36"><img src="http://devicemed.fr/wp-content/uploads/newsletter/medtec_france_nl.jpg" border="0" alt="" style="width:468px;text-align:center;"></a></td></tr> </tbody></table>

<table style="border-collapse:collapse;border-top:1px dotted #555;mso-table-lspace:0pt; mso-table-rspace:0pt;margin-left:10px;margin-top:10px;" width="700" id="top_news"><tbody><tr><td align="left"><h1 style="font-size:20px;color:#000000;font-family:Arial;">Sommaire de la newsletter du 12 mai 2015</h1></td></tr> </tbody></table><table width="700" style="border-bottom:0;border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:10px;" id="inhaltsverzeichnis"><tbody><tr><td><ul style="padding-left:20px;margin-top:0px;margin-bottom:0;">

<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/management/etudes-cliniques/1er-living-lab-prive-industriel-dedie-aux-solutions-de-e-sante/3097" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Kyomed&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/management/etudes-cliniques/1er-living-lab-prive-industriel-dedie-aux-solutions-de-e-sante/3097" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">1er Living Lab privé industriel dédié aux solutions de e-santé</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/helix-medical-acquiert-les-tubes-en-silicone-de-gore/3065" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Helix Medical&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/helix-medical-acquiert-les-tubes-en-silicone-de-gore/3065" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Helix Medical acquiert les tubes en silicone de Gore</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/deux-journees-pour-se-developper-plus-vite-a-linternational/3058" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Business France&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/deux-journees-pour-se-developper-plus-vite-a-linternational/3058" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Deux journées pour se développer plus vite à l’international</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/traitement_surface/le-diamant-une-source-dinnovation-precieuse-pour-les-revetements-de-dm/3091" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Neocoat&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/traitement_surface/le-diamant-une-source-dinnovation-precieuse-pour-les-revetements-de-dm/3091" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Le diamant : une source d’innovation précieuse pour les revêtements de DM</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/traitement_surface/implantation-ionique-multi-sources-pour-ameliorer-la-surface-des-dm/3077" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Bodycote&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/traitement_surface/implantation-ionique-multi-sources-pour-ameliorer-la-surface-des-dm/3077" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Implantation ionique multi-sources pour améliorer la surface des DM</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/metrologie_controle-sous-traitance-et-services/un-laboratiore-de-metrologie-dedie-aux-dm-en-plastiques/3086" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Précis &amp; Mans&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/metrologie_controle-sous-traitance-et-services/un-laboratiore-de-metrologie-dedie-aux-dm-en-plastiques/3086" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Un laboratoire de métrologie dédié aux DM en plastiques</span></a></li><!---->

</ul></td></tr></tbody></table>

<table width="700" style="margin-top:10px;border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:10px;" id="content"><tbody>

<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/management/etudes-cliniques/1er-living-lab-prive-industriel-dedie-aux-solutions-de-e-sante/3097" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/05/Kyomed.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/management/etudes-cliniques/1er-living-lab-prive-industriel-dedie-aux-solutions-de-e-sante/3097" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Kyomed</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/management/etudes-cliniques/1er-living-lab-prive-industriel-dedie-aux-solutions-de-e-sante/3097" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">1er Living Lab privé industriel dédié aux solutions de e-santé</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Destiné à tester des innovations sur les usagers, le principe de Living Lab se révèle essentiel au développement d’outils de santé efficaces. Basée sur ce principe et sur un réseau d’experts complémentaires, la société Kyomed [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/management/etudes-cliniques/1er-living-lab-prive-industriel-dedie-aux-solutions-de-e-sante/3097" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/helix-medical-acquiert-les-tubes-en-silicone-de-gore/3065" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/05/Helix-Medical.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/helix-medical-acquiert-les-tubes-en-silicone-de-gore/3065" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Helix Medical</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/helix-medical-acquiert-les-tubes-en-silicone-de-gore/3065" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Helix Medical acquiert les tubes en silicone de Gore</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Filiale du groupe Freundenberg, le fabricant de tubes médicaux Helix Medical&nbsp; vient de faire l’acquisition de la gamme de tubes en silicone de W. L. Gore &amp; Associates, Inc. (Gore), destinés aux installations de transfert [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/helix-medical-acquiert-les-tubes-en-silicone-de-gore/3065" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td colspan="2" style="border-top:1px dotted #555;padding-left:90px;"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;margin-top:10px;"><span style="font-size:12px;font-family:Helvetica,Arial,sans-serif;color:#999;">Annonce</span></p></td></tr><tr><td colspan="2" width="128" valign="top" style="width:128px;padding-bottom: 10px;padding-left:90px;">

<div style="padding:10px;width:500px;border:1px solid #333;">

<a href="http://www.device-med.fr/?url=http://p.protolabs.fr/lsr-white-paper?utm_campaign=fr-sos&amp;utm_medium=email&amp;utm_source=devicemed&amp;utm_content=en-lsrwp-0515&amp;id=35" target="_blank"><img style="border:solid 1px #FFFFFF;padding-right:10px;" width="100" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/newsletter/LSR_white_paper.jpg"></a>

<p style="margin:0px;padding-left:140px;"><a style="margin:0px;text-decoration:none;" href="http://www.device-med.fr/?url=http://p.protolabs.fr/lsr-white-paper?utm_campaign=fr-sos&amp;utm_medium=email&amp;utm_source=devicemed&amp;utm_content=en-lsrwp-0515&amp;id=35" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:black;">Le silicone liquide tient le choc !</span></a></p>

<p style="padding-left:140px;font-size:12px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Le livre blanc sur le silicone liquide (LSR) examine en détail le processus de moulage par injection de cette matière et 

offre des recommandations pour obtenir de meilleures pièces injectées en LSR. Pour plus d’informations, rendez-vous au salon Medtec, Hall A2, stand C133 !

<a style="text-decoration:none;color:#333;" href="http://www.device-med.fr/?url=http://p.protolabs.fr/lsr-white-paper?utm_campaign=fr-sos&amp;utm_medium=email&amp;utm_source=devicemed&amp;utm_content=en-lsrwp-0515&amp;id=35" target="_blank">Télécharger le livre blanc.</a>

</p></div></td></tr>

<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/evenements/deux-journees-pour-se-developper-plus-vite-a-linternational/3058" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/05/Business-France.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/deux-journees-pour-se-developper-plus-vite-a-linternational/3058" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Business France</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/deux-journees-pour-se-developper-plus-vite-a-linternational/3058" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Deux journées pour se développer plus vite à l’international</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Business France organise, les 23 et 24 juin prochains dans ses locaux, les Rencontres Internationales de la Santé. Dédié au développement international de la filière santé, l’événement réunira tous ses acteurs : fédérations professionnelles, pôles [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/deux-journees-pour-se-developper-plus-vite-a-linternational/3058" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/traitement_surface/le-diamant-une-source-dinnovation-precieuse-pour-les-revetements-de-dm/3091" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/05/Neocoat.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/traitement_surface/le-diamant-une-source-dinnovation-precieuse-pour-les-revetements-de-dm/3091" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Neocoat</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/traitement_surface/le-diamant-une-source-dinnovation-precieuse-pour-les-revetements-de-dm/3091" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Le diamant : une source d’innovation précieuse pour les revêtements de DM</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">La start-up suisse Neocoat a développé une technologie de dépôt de couches minces de diamant pour conférer la dureté et la résistance à l’usure de ce matériau à diverses pièces techniques, comme les prothèses et [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/traitement_surface/le-diamant-une-source-dinnovation-precieuse-pour-les-revetements-de-dm/3091" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/traitement_surface/implantation-ionique-multi-sources-pour-ameliorer-la-surface-des-dm/3077" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/05/Bodycote.png"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/traitement_surface/implantation-ionique-multi-sources-pour-ameliorer-la-surface-des-dm/3077" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Bodycote</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/traitement_surface/implantation-ionique-multi-sources-pour-ameliorer-la-surface-des-dm/3077" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Implantation ionique multi-sources pour améliorer la surface des DM</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Candidat au prix de l’Innovation A3TS 2015 pour son procédé d’implantation ionique multi-sources, Bodycote a mis en production une nouvelle machine de traitement de surface qui va permettre d’améliorer considérablement les propriétés mécaniques de dispositifs [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/traitement_surface/implantation-ionique-multi-sources-pour-ameliorer-la-surface-des-dm/3077" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/metrologie_controle-sous-traitance-et-services/un-laboratiore-de-metrologie-dedie-aux-dm-en-plastiques/3086" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/05/Précis-Mans.png"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/metrologie_controle-sous-traitance-et-services/un-laboratiore-de-metrologie-dedie-aux-dm-en-plastiques/3086" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Précis &amp; Mans</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/metrologie_controle-sous-traitance-et-services/un-laboratiore-de-metrologie-dedie-aux-dm-en-plastiques/3086" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Un laboratoire de métrologie dédié aux DM en plastiques</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Si la métrologie est indispensable à la garantie de qualité de tout DM, elle représente des défis particuliers dès qu’il s’agit de produits issus de l’assemblage de pièces en plastiques moulées. C’est dans ce domaine [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/metrologie_controle-sous-traitance-et-services/un-laboratiore-de-metrologie-dedie-aux-dm-en-plastiques/3086" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>

</tbody></table><!----><table width="704" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:0px" id="footer"><tbody><tr><td style="font-family:Arial; font-size:12px"><table cellspacing="0" width="702"><tbody><tr><td style="padding-bottom:10px;padding-top:10px;padding-left:10px;padding-right:10px;background-color:#c7c7c7"><table width="700"><tbody><tr><td align="left"><a href="http://news.vogel.de/inxmail2/d?q00wueoq0eqfngbii000000000000000ietwqbri3277"><img src="http://www.devicemed.fr/wp-content/themes/devicemed-responsive/images/newsletter/nl20/vogel_logo.gif" alt="Vogel Logo"></a></td><td align="right"></td></tr></tbody></table></td></tr><!----><tr><td align="center" style="font-size:11px;font-family:Arial,Helvetica,sans-serif;padding:10px;background-color:#d2d2d2;text-align:center;"><a style="text-decoration:none;" href="http://www.devicemed.fr/nous-contacter"><span style="font-size:12px;color:#b30f1d;text-align:center;">Contact</span></a></td></tr><!----><tr><td style="PADDING-BOTTOM: 10px; PADDING-TOP: 10px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; BACKGROUND-COLOR: #616161"><p style="FONT-SIZE: 11px; FONT-FAMILY: Arial, Helvetica, sans-serif; COLOR: #ffffff; LINE-HEIGHT: 18px">© The French language edition of DeviceMed is a publication of Evelyne Gisselbrecht, licensed by Vogel Business Media GmbH &amp; Co. KG, 97082 Wuerzburg/Germany.<br>

© Copyright of the trademark « DeviceMed » by Vogel Business Media GmbH &amp; Co. KG, 97082 Wuerzburg/Germany.<br>

Responsable du contenu rédactionnel sur <a style="text-decoration:none;color:#fff;" href="http://www.devicemed.fr/">www.devicemed.fr</a> : Evelyne Gisselbrecht, éditrice de DeviceMed, 33 rue du Puy-de-Dôme, 63370 Lempdes France</p></td></tr></tbody></table><!----><p></p></td></tr><tr><td style="text-align:center;font-family:Arial;font-size:11px">Le bulletin est adressé à <?php echo $mail; ?></td></tr>

<tr style="font-family:Arial;font-size:11px;color:#005ea8;text-decoration:underline;text-align:center;"><td><a style="text-decoration:none;" href="http://www.devicemed.fr/newsletter/desinscrire/<?php echo $mail; ?>"><span>Se désabonner</span></a></td></tr></tbody></table></td><td width="10" valign="top"></td><td width="160" valign="top"><table style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;"><tbody><tr><td style="padding-bottom:10px;"><a target="_blank" href="http://www.device-med.fr/?url=http://www.bgs.eu/homepage.html?&amp;no_cache=1&amp;L=2&amp;no_cache=1&amp;id=37"><img src="http://www.device-med.fr/wp-content/uploads/newsletter/bgs.jpg" width="127px"></a></td></tr>

<tr><td><div style="width:100%;padding-top:15px;"><a href="http://www.devicemed.fr/suppliers/" target="_blank">

<img width="127px" src="http://www.devicemed.fr/wp-content/uploads/newsletter/repertoirev6.jpg"></a></div></td></tr></tbody></table></td></tr></tbody></table></div>