<?php
	if(isset($_GET['mail']) && $_GET['mail'] != '') {
		$mail = $_GET['mail'];
	}
?>
<div style="width:850px !important;margin:0 auto;"><table cellspacing="0" cellpadding="0" width="850" border="0" align="center" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin:auto;" id="wrapper"><tbody><tr><td width="700" valign="top" style="background-color:#F1F1F1"><table style="border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt;margin-left:10px;" width="700"><tbody><tr><td><a style="border:none" href="http://www.devicemed.fr/"><img width="700" height="91" title="logo" alt="newsletter" src="http://www.device-med.fr/wp-content/uploads/newsletter/original.jpg"></a></td></tr></tbody></table><table style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;margin-left:10px;margin-top:10px;margin-bottom:10px;" width="700" id="top_news"><tbody><tr><td align="center"><a target="_blank" href="http://www.device-med.fr/?url=http://www.iconnect-exhibition.com&amp;id=33"><img src="http://devicemed.fr/wp-content/uploads/newsletter/iconnect.jpg" border="0" alt="" style="width:468px;text-align:center;"></a></td></tr> </tbody></table>

<table style="border-collapse:collapse;border-top:1px dotted #555;mso-table-lspace:0pt; mso-table-rspace:0pt;margin-left:10px;margin-top:10px;" width="700" id="top_news"><tbody><tr><td align="left"><h1 style="font-size:20px;color:#000000;font-family:Arial;">Sommaire de la newsletter du 28 avril 2015</h1></td></tr> </tbody></table><table width="700" style="border-bottom:0;border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:10px;" id="inhaltsverzeichnis"><tbody><tr><td><ul style="padding-left:20px;margin-top:0px;margin-bottom:0;">

<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/ephj-epmt-smt-tient-le-cap-en-2015/3021" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">EPHJ-EPMT-SMT&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/ephj-epmt-smt-tient-le-cap-en-2015/3021" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Le salon EPHJ-EPMT-SMT tient le cap en 2015</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/moteurs-et-entrainements/moteurs-piezoelectriques-lineaires-pour-micro-et-nano-positionnements/2995" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Cedrat Technologies S.A.&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/moteurs-et-entrainements/moteurs-piezoelectriques-lineaires-pour-micro-et-nano-positionnements/2995" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Moteurs piézoélectriques linéaires pour micro et nano-positionnements</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/le-laser-rencontrera-le-medical-le-24-septembre-2015-a-lyon/2984" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Club Laser &amp; Procédés&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/le-laser-rencontrera-le-medical-le-24-septembre-2015-a-lyon/2984" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Le laser rencontrera le médical le 24 septembre 2015 à Lyon</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/pharmapack-europe-2015-380-exposants-et-3000-visiteurs/2979" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">UBM Live&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/pharmapack-europe-2015-380-exposants-et-3000-visiteurs/2979" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Pharmapack Europe 2015 : 380 exposants et 3000 visiteurs</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/emballage_conditionnement/perforation-laser-demballage-flow-pack-en-vue-de-la-sterilisation/3013" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Ulma Packaging&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/emballage_conditionnement/perforation-laser-demballage-flow-pack-en-vue-de-la-sterilisation/3013" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Perforation laser d’emballage flow pack en vue de la stérilisation</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/electriques_electroniques/convertisseurs-dc-dc-de-3-w-6-w-et-10-w-pour-le-secteur-medical/3016" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Recom International&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/electriques_electroniques/convertisseurs-dc-dc-de-3-w-6-w-et-10-w-pour-le-secteur-medical/3016" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Convertisseurs DC-DC de 3 W, 6 W et 10 W dédiés au secteur médical</span></a></li><!---->

</ul></td></tr></tbody></table>

<table width="700" style="margin-top:10px;border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:10px;" id="content"><tbody>

<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/evenements/ephj-epmt-smt-tient-le-cap-en-2015/3021" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/04/EPHJ-EPMT-SMT.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/ephj-epmt-smt-tient-le-cap-en-2015/3021" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">EPHJ-EPMT-SMT</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/ephj-epmt-smt-tient-le-cap-en-2015/3021" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Le salon EPHJ-EPMT-SMT tient le cap en 2015</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">L’édition 2015 aura lieu du 2 au 5 juin à Palexpo, Genève. Malgré une conjoncture fragilisée par la hausse du franc suisse, les indicateurs sont au vert, notamment en ce qui concerne le secteur médical.
Fondé [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/ephj-epmt-smt-tient-le-cap-en-2015/3021" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/composants-oem/moteurs-et-entrainements/moteurs-piezoelectriques-lineaires-pour-micro-et-nano-positionnements/2995" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/04/Cedrat-Technologies-S.A..jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/moteurs-et-entrainements/moteurs-piezoelectriques-lineaires-pour-micro-et-nano-positionnements/2995" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Cedrat Technologies S.A.</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/moteurs-et-entrainements/moteurs-piezoelectriques-lineaires-pour-micro-et-nano-positionnements/2995" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Moteurs piézoélectriques linéaires pour micro et nano-positionnements</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">A la fois compacts, dynamiques et précis, les moteurs LSPA (Linear Stepping Piezo Actuator) de Cedrat Technologies permettent de développer divers types d’applications médicales innovantes en matière notamment de motorisation d’implants et de robotisation endoscopique. [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/moteurs-et-entrainements/moteurs-piezoelectriques-lineaires-pour-micro-et-nano-positionnements/2995" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/evenements/le-laser-rencontrera-le-medical-le-24-septembre-2015-a-lyon/2984" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/04/Club-Laser-Procédés.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/le-laser-rencontrera-le-medical-le-24-septembre-2015-a-lyon/2984" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Club Laser &amp; Procédés</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/le-laser-rencontrera-le-medical-le-24-septembre-2015-a-lyon/2984" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Le laser rencontrera le médical le 24 septembre 2015 à Lyon</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">En partenariat avec le salon Espace Laser et votre magazine DeviceMed, le Club Laser et Procédés (CLP) organise une demi-journée de conférences réparties en trois sessions : le traitement des pathologies par laser, l’usinage des [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/le-laser-rencontrera-le-medical-le-24-septembre-2015-a-lyon/2984" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/evenements/pharmapack-europe-2015-380-exposants-et-3000-visiteurs/2979" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/04/UBM-Live.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/pharmapack-europe-2015-380-exposants-et-3000-visiteurs/2979" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">UBM Live</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/pharmapack-europe-2015-380-exposants-et-3000-visiteurs/2979" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Pharmapack Europe 2015 : 380 exposants et 3000 visiteurs</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Bilan positif pour Pharmapack Europe, qui a regroupé 380 exposants à la Porte de Versailles de Paris, les 11 et 12 février derniers. Dédié au conditionnement de produits de santé et à l’administration des médicaments, [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/pharmapack-europe-2015-380-exposants-et-3000-visiteurs/2979" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/emballage_conditionnement/perforation-laser-demballage-flow-pack-en-vue-de-la-sterilisation/3013" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/04/Ulma-Packaging.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/emballage_conditionnement/perforation-laser-demballage-flow-pack-en-vue-de-la-sterilisation/3013" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Ulma Packaging</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/emballage_conditionnement/perforation-laser-demballage-flow-pack-en-vue-de-la-sterilisation/3013" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Perforation laser d’emballage flow pack en vue de la stérilisation</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Spécialisée dans la conception et la production d’équipements de conditionnement, Ulma Packaging propose une solution d’emballage en Flow Pack préparant, grâce à un système de perforation par laser, à tout type de stérilisation.
Ulma Packaging propose [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/emballage_conditionnement/perforation-laser-demballage-flow-pack-en-vue-de-la-sterilisation/3013" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/composants-oem/electriques_electroniques/convertisseurs-dc-dc-de-3-w-6-w-et-10-w-pour-le-secteur-medical/3016" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/04/Recom-International.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/electriques_electroniques/convertisseurs-dc-dc-de-3-w-6-w-et-10-w-pour-le-secteur-medical/3016" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Recom International</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/electriques_electroniques/convertisseurs-dc-dc-de-3-w-6-w-et-10-w-pour-le-secteur-medical/3016" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Convertisseurs DC-DC de 3 W, 6 W et 10 W dédiés au secteur médical</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">
Conditionnés en boitiers compacts DIP24, les convertisseurs de la série REM proposés par Recom sont certifiés 2 MOPP (Means of Patient Protection, moyen de protection du patient) pour des tensions de service allant jusqu’à 250Vac.


Malgré [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/electriques_electroniques/convertisseurs-dc-dc-de-3-w-6-w-et-10-w-pour-le-secteur-medical/3016" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>

</tbody></table><!----><table width="704" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:0px" id="footer"><tbody><tr><td style="font-family:Arial; font-size:12px"><table cellspacing="0" width="702"><tbody><tr><td style="padding-bottom:10px;padding-top:10px;padding-left:10px;padding-right:10px;background-color:#c7c7c7"><table width="700"><tbody><tr><td align="left"><a href="http://news.vogel.de/inxmail2/d?q00wueoq0eqfngbii000000000000000ietwqbri3277"><img src="http://www.devicemed.fr/wp-content/themes/devicemed-responsive/images/newsletter/nl20/vogel_logo.gif" alt="Vogel Logo"></a></td><td align="right"></td></tr></tbody></table></td></tr><!----><tr><td align="center" style="font-size:11px;font-family:Arial,Helvetica,sans-serif;padding:10px;background-color:#d2d2d2;text-align:center;"><a style="text-decoration:none;" href="http://www.devicemed.fr/nous-contacter"><span style="font-size:12px;color:#b30f1d;text-align:center;">Contact</span></a></td></tr><!----><tr><td style="PADDING-BOTTOM: 10px; PADDING-TOP: 10px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; BACKGROUND-COLOR: #616161"><p style="FONT-SIZE: 11px; FONT-FAMILY: Arial, Helvetica, sans-serif; COLOR: #ffffff; LINE-HEIGHT: 18px">© The French language edition of DeviceMed is a publication of Evelyne Gisselbrecht, licensed by Vogel Business Media GmbH &amp; Co. KG, 97082 Wuerzburg/Germany.<br>

© Copyright of the trademark « DeviceMed » by Vogel Business Media GmbH &amp; Co. KG, 97082 Wuerzburg/Germany.<br>

Responsable du contenu rédactionnel sur <a style="text-decoration:none;color:#fff;" href="http://www.devicemed.fr/">www.devicemed.fr</a> : Evelyne Gisselbrecht, éditrice de DeviceMed, 33 rue du Puy-de-Dôme, 63370 Lempdes France</p></td></tr></tbody></table><!----><p></p></td></tr><tr><td style="text-align:center;font-family:Arial;font-size:11px">Le bulletin est adressé à <?php echo $mail; ?></td></tr>

<tr style="font-family:Arial;font-size:11px;color:#005ea8;text-decoration:underline;text-align:center;"><td><a style="text-decoration:none;" href="http://www.devicemed.fr/newsletter/desinscrire/<?php echo $mail; ?>"><span>Se désabonner</span></a></td></tr></tbody></table></td><td width="10" valign="top"></td><td width="160" valign="top"><table style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;"><tbody><tr><td style="padding-bottom:10px;"><a target="_blank" href="http://www.device-med.fr/?url=http://www.devicemed.de/&amp;id=33"><img src="http://www.device-med.fr/wp-content/uploads/newsletter/devicemed_de.jpg" width="127px"></a></td></tr>

<tr><td><div style="width:100%;padding-top:15px;"><a href="http://www.devicemed.fr/suppliers/" target="_blank">

<img width="127px" src="http://www.devicemed.fr/wp-content/uploads/newsletter/repertoirev6.jpg"></a></div></td></tr></tbody></table></td></tr></tbody></table></div>