<?php
	if(isset($_GET['mail']) && $_GET['mail'] != '') {
		$mail = $_GET['mail'];
	}
?>
<div style="width:850px !important;margin:0 auto;"><table cellspacing="0" cellpadding="0" width="850" border="0" align="center" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin:auto;" id="wrapper"><tbody><tr><td width="700" valign="top" style="background-color:#F1F1F1"><table style="border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt;margin-left:10px;" width="700"><tbody><tr><td><a style="border:none" href="http://www.devicemed.fr/"><img width="700" height="91" title="logo" alt="newsletter" src="http://www.device-med.fr/wp-content/uploads/newsletter/original.jpg"></a></td></tr></tbody></table><table style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;margin-left:10px;margin-top:10px;margin-bottom:10px;" width="700" id="top_news"><tbody><tr><td align="center"><a target="_blank" href="http://www.device-med.fr/?url=http://www.knf.fr/produits/pompes-de-laboratoire/&amp;id=16"><img src="http://devicemed.fr/wp-content/uploads/newsletter/knf.gif" border="0" alt="" style="margin-top:5px;width:468px;text-align:center;"></a></td></tr> </tbody></table>

<table style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;margin-left:10px;margin-top:10px;" width="700" id="top_news"><tbody><tr><td align="left"><h1 style="font-size:20px;color:#000000;font-family:Arial;">Sommaire de la newsletter du 3 mars 2015</h1></td></tr> </tbody></table><table width="700" style="border-bottom:0;border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:10px;" id="inhaltsverzeichnis"><tbody><tr><td><ul style="padding-left:20px;margin-top:0px;margin-bottom:0;"><li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/industrie-lyon-2015-attend-20000-visiteur-du-7-au-10-avril/2561" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;">GL Events&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/industrie-lyon-2015-attend-20000-visiteur-du-7-au-10-avril/2561" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Industrie Lyon 2015 attend 20000 visiteurs du 7 au 10 avril</span></a></li><!---->

<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/imprimantes-3d-pour-protheses-dentaires-et-auditives/2573" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;">Kreos&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/imprimantes-3d-pour-protheses-dentaires-et-auditives/2573" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Imprimantes 3D pour prothèses dentaires et auditives</span></a></li><!---->

<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/conception-et-installation-de-cellules-robotisees-sur-mesure/2585" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;">Techplus&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/conception-et-installation-de-cellules-robotisees-sur-mesure/2585" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Conception et installation de cellules robotisées sur mesure</span></a></li><!---->

<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/logiciel-de-cfaoerp-pour-la-fabrication-mecanique/2606" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;">Missler Software&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/logiciel-de-cfaoerp-pour-la-fabrication-mecanique/2606" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Logiciel de CFAO/ERP pour la fabrication mécanique</span></a></li><!---->

<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/outils-de-fraisage-pour-tous-types-dapplications/2603" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;">Dormer Pramet&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/outils-de-fraisage-pour-tous-types-dapplications/2603" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Outils de fraisage pour tous types d’applications</span></a></li><!---->

<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/palpeur-analogique-haute-performance-pour-mesure-3d/2593" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;">Hexagon&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/palpeur-analogique-haute-performance-pour-mesure-3d/2593" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Palpeur analogique haute performance pour mesure 3D</span></a></li><!---->

</ul></td></tr></tbody></table>

<table width="700" style="margin-top:10px;border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:10px" id="content"><tbody>

<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/industrie-lyon-2015-attend-20000-visiteur-du-7-au-10-avril/2561" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/03/Photo-INDUSTRIE-2-755.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/industrie-lyon-2015-attend-20000-visiteur-du-7-au-10-avril/2561" target="_blank"><span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">GL Events</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/industrie-lyon-2015-attend-20000-visiteur-du-7-au-10-avril/2561" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Industrie Lyon 2015 attend 20000 visiteurs du 7 au 10 avril</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Après Paris l’an dernier, c’est à Lyon (Eurexpo) d’accueillir cette année le salon des technologies de production. Comme en 2013, il regroupera 850 exposants, sur 50000 m2 d’exposition, représentant 9 secteurs industriels, plus celui de [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/industrie-lyon-2015-attend-20000-visiteur-du-7-au-10-avril/2561" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/imprimantes-3d-pour-protheses-dentaires-et-auditives/2573" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/03/DMF_NL5_Kreos-Fotodent-Jaw-755.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/imprimantes-3d-pour-protheses-dentaires-et-auditives/2573" target="_blank"><span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Kreos</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/imprimantes-3d-pour-protheses-dentaires-et-auditives/2573" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Imprimantes 3D pour prothèses dentaires et auditives</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Présent dans le Village Impression 3D d’Industrie Lyon, aux côtés de la société Prodways, Kreos présentera de nombreux équipements de prototypage, comme un scanner 3D, un bras de sculpture numérique, une machine d’usinage, et une [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/imprimantes-3d-pour-protheses-dentaires-et-auditives/2573" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td colspan="2" style="border-top:1px dotted #555;padding-left:90px;"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;margin-top:10px;"><span style="font-size:12px;font-family:Helvetica,Arial,sans-serif;color:#999;">Annonce</span></p></td></tr><tr><td colspan="2" width="128" valign="top" style="width:128px;padding-bottom: 10px;padding-left:90px;">

<div style="padding:10px;width:500px;border:1px solid #333;">

<a href="http://www.device-med.fr/?url=http://rvs.gipco-adns.com/&amp;id=18" target="_blank"><img style="border:solid 1px #FFFFFF;" width="100" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/newsletter/vigipharm.jpg"></a>

<p style="margin:0px;padding-left:140px;"><a style="margin:0px;text-decoration:none;" href="http://www.device-med.fr/?url=http://rvs.gipco-adns.com/&amp;id=18" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:black;">La Matériovigilance au rendez-vous</span></a></p>

<p style="padding-left:140px;font-size:12px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Ce rassemblement national aura lieu le 26/03/15 à Montpellier. Pour la Matériovigilance, il réunira institutionnels et industriels du secteur du DM et sera animé par des intervenants reconnus et recommandés par le SNITEM. C'est l’occasion d’anticiper le projet de loi santé et le futur règlement européen. <a style="text-decoration:none;" href="http://www.device-med.fr/?url=http://rvs.gipco-adns.com/&amp;id=18" target="_blank"><span style="color:#005ea8;">Pour en savoir plus</span></a></p></div></td></tr>

<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/conception-et-installation-de-cellules-robotisees-sur-mesure/2585" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/03/DMF_NL5_2015_TechPlus-TITRE-1-2-755.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/conception-et-installation-de-cellules-robotisees-sur-mesure/2585" target="_blank"><span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Techplus</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/conception-et-installation-de-cellules-robotisees-sur-mesure/2585" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Conception et installation de cellules robotisées sur mesure</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Fidèle au salon Industrie, Techplus présentera son savoir-faire en matière d’ingénierie robotique, qu’elle met régulièrement au service de sous-traitants et de fabricants de dispositifs médicaux.
Créée en 1994, membre du Groupe Robotique du Symop et partenaire [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/conception-et-installation-de-cellules-robotisees-sur-mesure/2585" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/logiciel-de-cfaoerp-pour-la-fabrication-mecanique/2606" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/03/Missler-Software-755.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/logiciel-de-cfaoerp-pour-la-fabrication-mecanique/2606" target="_blank"><span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Missler Software</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/logiciel-de-cfaoerp-pour-la-fabrication-mecanique/2606" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Logiciel de CFAO/ERP pour la fabrication mécanique</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Editeur de TopSolid, la société Missler Software annonce la septième génération de ce logiciel de CAO/FAO/ERP.&nbsp;Une&nbsp;nouvelle version&nbsp;qui représente un bond en avant significatif, avec des nouveautés comme la parallélisation, l’usage du PDM, la compatibilité Web, [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/logiciel-de-cfaoerp-pour-la-fabrication-mecanique/2606" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/outils-de-fraisage-pour-tous-types-dapplications/2603" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/03/Safety-PNP_003-755.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/outils-de-fraisage-pour-tous-types-dapplications/2603" target="_blank"><span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Dormer Pramet</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/outils-de-fraisage-pour-tous-types-dapplications/2603" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Outils de fraisage pour tous types d’applications</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Désormais réunies et intégrées au groupe Dormer Pramet sur le territoire français, les fabricants d’outils d’usinage Dormer et Safety annoncent une avalanche de nouveaux produits, qui permettent de couvrir un large éventail d’applications.
Spécialiste des outils [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/outils-de-fraisage-pour-tous-types-dapplications/2603" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/palpeur-analogique-haute-performance-pour-mesure-3d/2593" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/03/Hexagon-755.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/palpeur-analogique-haute-performance-pour-mesure-3d/2593" target="_blank"><span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Hexagon</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/palpeur-analogique-haute-performance-pour-mesure-3d/2593" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Palpeur analogique haute performance pour mesure 3D</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Destiné aux machines Leitz de très haute précision, le capteur de scanning HP-S-X5 HD se distingue par la possibilité d’utiliser un&nbsp; stylet de 800 mm de long tout en assurant une mesure tridimensionnelle précise et [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/palpeur-analogique-haute-performance-pour-mesure-3d/2593" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>

</tbody></table><!----><table width="704" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:0px" id="footer"><tbody><tr><td style="font-family:Arial; font-size:12px"><table cellspacing="0" width="702"><tbody><tr><td style="padding-bottom:10px;padding-top:10px;padding-left:10px;padding-right:10px;background-color:#c7c7c7"><table width="700"><tbody><tr><td align="left"><a href="http://news.vogel.de/inxmail2/d?q00wueoq0eqfngbii000000000000000ietwqbri3277"><img src="http://www.devicemed.fr/wp-content/themes/devicemed-responsive/images/newsletter/nl20/vogel_logo.gif" alt="Vogel Logo"></a></td><td align="right"></td></tr></tbody></table></td></tr><!----><tr><td align="center" style="font-size:11px;font-family:Arial,Helvetica,sans-serif;padding:10px;background-color:#d2d2d2;text-align:center;"><a style="text-decoration:none;" href="http://www.devicemed.fr/nous-contacter"><span style="font-size:12px;color:#b30f1d;text-align:center;">Contact</span></a></td></tr><!----><tr><td style="PADDING-BOTTOM: 10px; PADDING-TOP: 10px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; BACKGROUND-COLOR: #616161"><p style="FONT-SIZE: 11px; FONT-FAMILY: Arial, Helvetica, sans-serif; COLOR: #ffffff; LINE-HEIGHT: 18px">© The French language edition of DeviceMed is a publication of Evelyne Gisselbrecht, licensed by Vogel Business Media GmbH &amp; Co. KG, 97082 Wuerzburg/Germany.<br>

© Copyright of the trademark « DeviceMed » by Vogel Business Media GmbH &amp; Co. KG, 97082 Wuerzburg/Germany.<br>

Responsable du contenu rédactionnel sur <a style="text-decoration:none;color:#fff;" href="http://www.devicemed.fr/">www.devicemed.fr</a> : Evelyne Gisselbrecht, éditrice de DeviceMed, 33 rue du Puy-de-Dôme, 63370 Lempdes France</p></td></tr></tbody></table><!----><p></p></td></tr><tr><td style="text-align:center;font-family:Arial;font-size:11px">Le bulletin est adressé à <?php echo $mail; ?></td></tr>

<tr style="font-family:Arial;font-size:11px;color:#005ea8;text-decoration:underline;text-align:center;"><td><a style="text-decoration:none;" href="http://www.devicemed.fr/newsletter/desinscrire/<?php echo $mail; ?>"><span>Se désabonner</span></a></td></tr></tbody></table></td><td width="10" valign="top"></td><td width="160" valign="top"><table style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;"><tbody><tr><td><a href="http://www.device-med.fr/?url=http://www.devicemed.de/&amp;id=17"><img src="http://www.device-med.fr/wp-content/uploads/newsletter/devicemed_de.jpg" width="127px"></a></td></tr></tbody></table></td></tr></tbody></table></div>