<?php
	if(isset($_GET['mail']) && $_GET['mail'] != '') {
		$mail = $_GET['mail'];
	}
?>
<div style="width:850px !important;margin:0 auto;"><table cellspacing="0" cellpadding="0" width="850" border="0" align="center" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin:auto;" id="wrapper"><tbody><tr><td width="700" valign="top" style="background-color:#F1F1F1"><table style="border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt;margin-left:10px;" width="700"><tbody><tr><td><a style="border:none" href="http://www.devicemed.fr/"><img width="700" height="91" title="logo" alt="newsletter" src="http://www.device-med.fr/wp-content/uploads/newsletter/original.jpg"></a></td></tr></tbody></table><table style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;margin-left:10px;margin-top:10px;margin-bottom:10px;" width="700" id="top_news"><tbody><tr><td align="center"><a target="_blank" href="http://www.device-med.fr/?url=http://www.knf.fr/produits/pompes-de-laboratoire/&amp;id=48"><img src="http://devicemed.fr/wp-content/uploads/banniere/knf.gif" border="0" alt="" style="width:468px;text-align:center;"></a></td></tr> </tbody></table>

<table style="border-collapse:collapse;border-top:1px dotted #555;mso-table-lspace:0pt; mso-table-rspace:0pt;margin-left:10px;margin-top:10px;" width="700" id="top_news"><tbody><tr><td align="left"><h1 style="font-size:20px;color:#000000;font-family:Arial;">Sommaire de la newsletter du 9 juin 2015</h1></td></tr> </tbody></table><table width="700" style="border-bottom:0;border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:10px;" id="inhaltsverzeichnis"><tbody><tr><td><ul style="padding-left:20px;margin-top:0px;margin-bottom:0;">

<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/le-salon-ephj-epmt-smt-a-franchi-la-barre-des-20000-entrees-en-hausse-de-11-par-rapport-a-2014/3541" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">EPHJ-EPMT-SMT&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/le-salon-ephj-epmt-smt-a-franchi-la-barre-des-20000-entrees-en-hausse-de-11-par-rapport-a-2014/3541" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Le salon a franchi la barre des 20000 entrées, une hausse de 11% par rapport à 2014</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/tubes/tubulures-en-peek-de-qualite-medicale-avec-options-sur-mesure/3494" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Teleflex Medical OEM&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/tubes/tubulures-en-peek-de-qualite-medicale-avec-options-sur-mesure/3494" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Tubulures en PEEK de qualité médicale, avec options sur mesure</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/molex-acquiert-soligie-et-ses-competences-en-matiere-delectronique-imprimee/3536" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Molex Incorporated&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/molex-acquiert-soligie-et-ses-competences-en-matiere-delectronique-imprimee/3536" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Le fabricant acquiert Soligie et ses compétences en matière d’électronique imprimée</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/moteurs-et-entrainements/guidage-lineaire-amagnetique-le-plus-leger-du-monde/3533" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">igus SARL&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/moteurs-et-entrainements/guidage-lineaire-amagnetique-le-plus-leger-du-monde/3533" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Guidage linéaire amagnétique le plus léger du monde</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/workshop-sur-la-maitrise-de-la-contamination-en-salles-propres-les-8-et-9-octobre-2015/3547" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Aspec&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/workshop-sur-la-maitrise-de-la-contamination-en-salles-propres-les-8-et-9-octobre-2015/3547" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Workshop sur la maîtrise de la contamination des matériaux en salle propre les 8 et 9 octobre 2015</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/management/conseil/le-management-des-risques-demarche-fondamentale-de-la-reglementation-sur-les-dm/3554" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Préiso&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/management/conseil/le-management-des-risques-demarche-fondamentale-de-la-reglementation-sur-les-dm/3554" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Le management des risques : démarche fondamentale de la règlementation sur les DM</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/electriques_electroniques/technologie-de-rupture-en-vue-pour-la-spectrometrie-infrarouge/3442" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">mirSense&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/electriques_electroniques/technologie-de-rupture-en-vue-pour-la-spectrometrie-infrarouge/3442" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Technologie de rupture en vue pour la spectrométrie infrarouge</span></a></li><!---->

</ul></td></tr></tbody></table>

<table width="700" style="margin-top:10px;border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:10px;" id="content"><tbody>

<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/evenements/le-salon-ephj-epmt-smt-a-franchi-la-barre-des-20000-entrees-en-hausse-de-11-par-rapport-a-2014/3541" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/06/theWATCHES.tv_-e1433775792353.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/le-salon-ephj-epmt-smt-a-franchi-la-barre-des-20000-entrees-en-hausse-de-11-par-rapport-a-2014/3541" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">EPHJ-EPMT-SMT</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/le-salon-ephj-epmt-smt-a-franchi-la-barre-des-20000-entrees-en-hausse-de-11-par-rapport-a-2014/3541" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Le salon a franchi la barre des 20000 entrées, une hausse de 11% par rapport à 2014</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Pour sa quatorzième année, le salon EPHJ-EPMT-SMT affiche un bilan très positif au terme d’une édition qui s’est achevée vendredi dernier avec une fréquentation et un nombre d’exposants en hausse, malgré une période délicate.
Le renforcement [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/le-salon-ephj-epmt-smt-a-franchi-la-barre-des-20000-entrees-en-hausse-de-11-par-rapport-a-2014/3541" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/composants-oem/tubes/tubulures-en-peek-de-qualite-medicale-avec-options-sur-mesure/3494" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/06/Teleflex-Medical-OEM.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/tubes/tubulures-en-peek-de-qualite-medicale-avec-options-sur-mesure/3494" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Teleflex Medical OEM</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/tubes/tubulures-en-peek-de-qualite-medicale-avec-options-sur-mesure/3494" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Tubulures en PEEK de qualité médicale, avec options sur mesure</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Figurant parmi les leaders mondiaux en matière d’extrusion de pièces de précision et de cathéters complexes, Teleflex Medical OEM annonce l’intégration du PEEK à un large portefeuille de matériaux spéciaux destinés aux technologies médicales.
Le PEEK [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/tubes/tubulures-en-peek-de-qualite-medicale-avec-options-sur-mesure/3494" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td colspan="2" style="border-top:1px dotted #555;padding-left:90px;"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;margin-top:10px;"><span style="font-size:12px;font-family:Helvetica,Arial,sans-serif;color:#999;">Annonce</span></p></td></tr><tr><td colspan="2" width="128" valign="top" style="width:128px;padding-bottom: 10px;padding-left:90px;">

<div style="padding:10px;width:500px;border:1px solid #333;">

<a href="http://www.device-med.fr/?url=https%3A%2F%2Fregistration.n200.com%2Fsurvey%2F3ijofmsjjh1is%2Fstart%3Ftranslation%3D06br8dhkh910n%3Futm_campaign%3Dfr-sos%26utm_medium%3Demail%26utm_source%3Dmd%26utm_content%3Deb-tradesw-0615&amp;id=49" target="_blank"><img style="border:solid 1px #FFFFFF;padding-right:10px;" width="100" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/banniere/protolabs_nl_09.jpg"></a>

<p style="margin:0px;padding-left:140px;"><a style="margin:0px;text-decoration:none;" href="http://www.device-med.fr/?url=https%3A%2F%2Fregistration.n200.com%2Fsurvey%2F3ijofmsjjh1is%2Fstart%3Ftranslation%3D06br8dhkh910n%3Futm_campaign%3Dfr-sos%26utm_medium%3Demail%26utm_source%3Dmd%26utm_content%3Deb-tradesw-0615&amp;id=49" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:black;">Proto Labs vient à votre rencontre !</span></a></p>

<p style="padding-left:140px;font-size:12px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Venez retrouver Proto Labs lors de cette nouvelle édition du salon du MEDTEC France. Celui-ci se déroulera du 10 au 11 Juin 2015 au centre Micropolis de Besançon. Notre équipe vous accueillera au stand C 133 du Hall A2. 

Pour obtenir votre entrée, inscrivez-vous <a style="text-decoration:none;" href="http://www.device-med.fr/?url=https%3A%2F%2Fregistration.n200.com%2Fsurvey%2F3ijofmsjjh1is%2Fstart%3Ftranslation%3D06br8dhkh910n%3Futm_campaign%3Dfr-sos%26utm_medium%3Demail%26utm_source%3Dmd%26utm_content%3Deb-tradesw-0615&amp;id=49" target="_blank">ici</a>.

</p></div></td></tr>

<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/molex-acquiert-soligie-et-ses-competences-en-matiere-delectronique-imprimee/3536" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/06/Soligie.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/molex-acquiert-soligie-et-ses-competences-en-matiere-delectronique-imprimee/3536" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Molex Incorporated</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/molex-acquiert-soligie-et-ses-competences-en-matiere-delectronique-imprimee/3536" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Le fabricant acquiert Soligie et ses compétences en matière d’électronique imprimée</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Fabricant mondial de solutions d’interconnexion, Molex vient d’annoncer l’acquisition de certains actifs de la société Soligie, spécialisée dans les solutions d’électronique imprimée destinées notamment aux applications médicales.
Vecteur d’innovation dans toutes les industries, l’électronique progresse rapidement [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/molex-acquiert-soligie-et-ses-competences-en-matiere-delectronique-imprimee/3536" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/composants-oem/moteurs-et-entrainements/guidage-lineaire-amagnetique-le-plus-leger-du-monde/3533" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/06/igus.jpeg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/moteurs-et-entrainements/guidage-lineaire-amagnetique-le-plus-leger-du-monde/3533" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">igus SARL</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/moteurs-et-entrainements/guidage-lineaire-amagnetique-le-plus-leger-du-monde/3533" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Guidage linéaire amagnétique le plus léger du monde</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Pour répondre au besoin de légèreté et d’amagnétisme qu’on trouve par exemple dans les applications de radiographie médicale, igus vient de mettre&nbsp;au point un profilé en carbone autorisant des courses jusqu’à 2000 millimètres.
La fibre de [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/moteurs-et-entrainements/guidage-lineaire-amagnetique-le-plus-leger-du-monde/3533" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/evenements/workshop-sur-la-maitrise-de-la-contamination-en-salles-propres-les-8-et-9-octobre-2015/3547" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/06/Aspec.png"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/workshop-sur-la-maitrise-de-la-contamination-en-salles-propres-les-8-et-9-octobre-2015/3547" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Aspec</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/workshop-sur-la-maitrise-de-la-contamination-en-salles-propres-les-8-et-9-octobre-2015/3547" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Workshop sur la maîtrise de la contamination des matériaux en salle propre les 8 et 9 octobre 2015</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Association professionnelle&nbsp;française de référence dans le domaine de la salle propre et des environnements maîtrisés, l’ASPEC propose un nouvel événement régional les 8 et 9 octobre prochains à Aix en Provence, en partenariat avec Expert’Labs.
La [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/workshop-sur-la-maitrise-de-la-contamination-en-salles-propres-les-8-et-9-octobre-2015/3547" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/management/conseil/le-management-des-risques-demarche-fondamentale-de-la-reglementation-sur-les-dm/3554" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/06/Fotolia.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/management/conseil/le-management-des-risques-demarche-fondamentale-de-la-reglementation-sur-les-dm/3554" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Préiso</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/management/conseil/le-management-des-risques-demarche-fondamentale-de-la-reglementation-sur-les-dm/3554" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Le management des risques : démarche fondamentale de la règlementation sur les DM</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Nécessaire au marquage CE de tout dispositif médical, le management des risques est une affaire d’experts. Il existe des consultants spécialisés dans ce domaine, comme Sébastien Ruiz, Président fondateur du cabinet Préiso, et son collaborateur [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/management/conseil/le-management-des-risques-demarche-fondamentale-de-la-reglementation-sur-les-dm/3554" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/composants-oem/electriques_electroniques/technologie-de-rupture-en-vue-pour-la-spectrometrie-infrarouge/3442" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/05/mirSense.png"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/electriques_electroniques/technologie-de-rupture-en-vue-pour-la-spectrometrie-infrarouge/3442" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">mirSense</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/electriques_electroniques/technologie-de-rupture-en-vue-pour-la-spectrometrie-infrarouge/3442" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Technologie de rupture en vue pour la spectrométrie infrarouge</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Alcatel-Lucent, Thales et le CEA-Leti accompagnent le lancement de mirSense, une startup qui va démocratiser la spectrométrie infrarouge, destinée à l’identification fiable et rapide des molécules organiques.
Dans le cadre de leur partenariat au sein du [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/electriques_electroniques/technologie-de-rupture-en-vue-pour-la-spectrometrie-infrarouge/3442" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>

</tbody></table><!----><table width="704" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:0px" id="footer"><tbody><tr><td style="font-family:Arial; font-size:12px"><table cellspacing="0" width="702"><tbody><tr><td style="padding-bottom:10px;padding-top:10px;padding-left:10px;padding-right:10px;background-color:#c7c7c7"><table width="700"><tbody><tr><td align="left"><a href="http://news.vogel.de/inxmail2/d?q00wueoq0eqfngbii000000000000000ietwqbri3277"><img src="http://www.devicemed.fr/wp-content/themes/devicemed-responsive/images/newsletter/nl20/vogel_logo.gif" alt="Vogel Logo"></a></td><td align="right"></td></tr></tbody></table></td></tr><!----><tr><td align="center" style="font-size:11px;font-family:Arial,Helvetica,sans-serif;padding:10px;background-color:#d2d2d2;text-align:center;"><a style="text-decoration:none;" href="http://www.devicemed.fr/nous-contacter"><span style="font-size:12px;color:#b30f1d;text-align:center;">Contact</span></a></td></tr><!----><tr><td style="PADDING-BOTTOM: 10px; PADDING-TOP: 10px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; BACKGROUND-COLOR: #616161"><p style="FONT-SIZE: 11px; FONT-FAMILY: Arial, Helvetica, sans-serif; COLOR: #ffffff; LINE-HEIGHT: 18px">© The French language edition of DeviceMed is a publication of Evelyne Gisselbrecht, licensed by Vogel Business Media GmbH &amp; Co. KG, 97082 Wuerzburg/Germany.<br>

© Copyright of the trademark « DeviceMed » by Vogel Business Media GmbH &amp; Co. KG, 97082 Wuerzburg/Germany.<br>

Responsable du contenu rédactionnel sur <a style="text-decoration:none;color:#fff;" href="http://www.devicemed.fr/">www.devicemed.fr</a> : Evelyne Gisselbrecht, éditrice de DeviceMed, 33 rue du Puy-de-Dôme, 63370 Lempdes France</p></td></tr></tbody></table><!----><p></p></td></tr><tr><td style="text-align:center;font-family:Arial;font-size:11px">Le bulletin est adressé à <?php echo $mail; ?></td></tr>

<tr style="font-family:Arial;font-size:11px;color:#005ea8;text-decoration:underline;text-align:center;"><td><a style="text-decoration:none;" href="http://www.devicemed.fr/newsletter/desinscrire/<?php echo $mail; ?>"><span>Se désabonner</span></a></td></tr></tbody></table></td><td width="10" valign="top"></td><td width="160" valign="top"><table style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;"><tbody><tr><td style="padding-bottom:10px;"><a target="_blank" href="http://www.device-med.fr/?url=http://www.devicemed.de/&amp;id=47"><img src="http://www.device-med.fr/wp-content/uploads/newsletter/devicemed_de.jpg" width="127px"></a></td></tr>

<tr><td><div style="width:100%;padding-top:15px;"><a href="http://www.devicemed.fr/suppliers/" target="_blank">

<img width="127px" src="http://www.devicemed.fr/wp-content/uploads/newsletter/repertoirev6.jpg"></a></div></td></tr></tbody></table></td></tr></tbody></table></div>