<?php
	if(isset($_GET['mail']) && $_GET['mail'] != '') {
		$mail = $_GET['mail'];
	}
?>
<div style="width:850px !important;margin:0 auto;"><table cellspacing="0" cellpadding="0" width="850" border="0" align="center" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin:auto;" id="wrapper"><tbody><tr><td width="700" valign="top" style="background-color:#F1F1F1"><table style="border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt;margin-left:10px;" width="700"><tbody><tr><td><a style="border:none" href="http://www.devicemed.fr/"><img width="700" height="91" title="logo" alt="newsletter" src="http://www.device-med.fr/wp-content/uploads/newsletter/original.jpg"></a></td></tr></tbody></table><table style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;margin-left:10px;margin-top:10px;margin-bottom:10px;" width="700" id="top_news"><tbody><tr><td align="center"><a target="_blank" href="http://www.device-med.fr/?url=https://lumen.ni.com/nicif/f/seminarslides103/frwe1503appmed/content.xhtml?cid=Advertising-Cross_Program-France-none&amp;metc=mtcyy6&amp;id=26"><img src="http://devicemed.fr/wp-content/uploads/newsletter/ni.gif" border="0" alt="" style="width:468px;text-align:center;"></a></td></tr> </tbody></table>

<table style="border-collapse:collapse;border-top:1px dotted #555;mso-table-lspace:0pt; mso-table-rspace:0pt;margin-left:10px;margin-top:10px;" width="700" id="top_news"><tbody><tr><td align="left"><h1 style="font-size:20px;color:#000000;font-family:Arial;">Sommaire de la newsletter du 14 avril 2015</h1></td></tr> </tbody></table><table width="700" style="border-bottom:0;border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:10px;" id="inhaltsverzeichnis"><tbody><tr><td><ul style="padding-left:20px;margin-top:0px;margin-bottom:0;">

<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/associations_professionnelles/lafcros-salarme-de-la-perte-de-competitivite-de-la-recherche-clinique-francaise/2843" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">AFCROs&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/associations_professionnelles/lafcros-salarme-de-la-perte-de-competitivite-de-la-recherche-clinique-francaise/2843" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">L’assocation s’alarme de la perte de compétitivité de la Recherche Clinique française</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/minalogic-et-le-pole-optique-rhone-alpes-fusionnent/2836" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Minalogic&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/minalogic-et-le-pole-optique-rhone-alpes-fusionnent/2836" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Minalogic et le Pôle Optique Rhône-Alpes fusionnent</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/electriques_electroniques/circuit-bluetooth-smart-pour-les-dm-connectes-portables/2887" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Dialog Semiconductor&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/electriques_electroniques/circuit-bluetooth-smart-pour-les-dm-connectes-portables/2887" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Circuit Bluetooth Smart pour les DM connectés portables</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/materiaux/adhesifs/5-secondes-pour-coller-des-dm-tout-en-souplesse/2872" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Henkel&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/materiaux/adhesifs/5-secondes-pour-coller-des-dm-tout-en-souplesse/2872" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">5 secondes pour coller des DM tout en souplesse</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/assemblage-sous-traitance-et-services/pour-des-tubes-et-raccords-medicaux-proprement-colles/2870" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Syneo&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/assemblage-sous-traitance-et-services/pour-des-tubes-et-raccords-medicaux-proprement-colles/2870" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Pour des tubes et raccords médicaux proprement collés</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/comparateur-optique-sans-contact/2864" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Stil S.A&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/comparateur-optique-sans-contact/2864" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Comparateur optique sans contact</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/electriques_electroniques/alimentation-de-30-watts-ultra-compacte-pour-le-medical/2830" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">XP Power&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/electriques_electroniques/alimentation-de-30-watts-ultra-compacte-pour-le-medical/2830" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Alimentation de 30 Watts ultra-compacte pour le médical</span></a></li><!---->

</ul></td></tr></tbody></table>

<table width="700" style="margin-top:10px;border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:10px;" id="content"><tbody>

<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/associations_professionnelles/lafcros-salarme-de-la-perte-de-competitivite-de-la-recherche-clinique-francaise/2843" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/04/Shutterstock.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/associations_professionnelles/lafcros-salarme-de-la-perte-de-competitivite-de-la-recherche-clinique-francaise/2843" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">AFCROs</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/associations_professionnelles/lafcros-salarme-de-la-perte-de-competitivite-de-la-recherche-clinique-francaise/2843" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">L’assocation s’alarme de la perte de compétitivité de la Recherche Clinique française</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Les entreprises de la Recherche Clinique s’associent à l’inquiétude de France Biotech et appellent le gouvernement à une action rapide pour sauvegarder l’excellence de ce secteur et préserver ses emplois hautement qualifiés.
L’AFCROs (Association française des&nbsp;entreprises [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/associations_professionnelles/lafcros-salarme-de-la-perte-de-competitivite-de-la-recherche-clinique-francaise/2843" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/minalogic-et-le-pole-optique-rhone-alpes-fusionnent/2836" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/04/Pierre-Jayet-AEPI.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/minalogic-et-le-pole-optique-rhone-alpes-fusionnent/2836" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Minalogic</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/minalogic-et-le-pole-optique-rhone-alpes-fusionnent/2836" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Minalogic et le Pôle Optique Rhône-Alpes fusionnent</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Spécialisé dans la micro-nanoélectronique et le logiciel, le pôle de compétitivité Minalogic annonce son rapprochement avec le Pôle Optique Rhône-Alpes (ORA), dont l’objet est le développement et la mise en valeur de la filière optique-photonique [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/minalogic-et-le-pole-optique-rhone-alpes-fusionnent/2836" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr style="border-top:1px dotted #555;"><td align="center" colspan="2"><a target="_blank" href="http://www.device-med.fr/?url=http://www.iconnect-exhibition.com&amp;id=27">

<img src="http://devicemed.fr/wp-content/uploads/newsletter/iconnect.jpg" border="0" alt="" style="margin-top:5px;width:468px;text-align:center;margin-bottom:5px;">

</a></td></tr> 


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/composants-oem/electriques_electroniques/circuit-bluetooth-smart-pour-les-dm-connectes-portables/2887" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/04/da14680-pr-image.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/electriques_electroniques/circuit-bluetooth-smart-pour-les-dm-connectes-portables/2887" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Dialog Semiconductor</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/electriques_electroniques/circuit-bluetooth-smart-pour-les-dm-connectes-portables/2887" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Circuit Bluetooth Smart pour les DM connectés portables</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">
Surfant sur la vague du «&nbsp;wearable&nbsp;»,&nbsp;la société&nbsp;Dialog Semiconductor annonce un système sur une puce (SoC) destiné à la conception de dispositifs médicaux connectés ultra-compacts. Ce composant regroupe de nombreux circuits, y compris une interface BlueTooth [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/electriques_electroniques/circuit-bluetooth-smart-pour-les-dm-connectes-portables/2887" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/materiaux/adhesifs/5-secondes-pour-coller-des-dm-tout-en-souplesse/2872" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/04/Henkel-Technologies.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/materiaux/adhesifs/5-secondes-pour-coller-des-dm-tout-en-souplesse/2872" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Henkel</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/materiaux/adhesifs/5-secondes-pour-coller-des-dm-tout-en-souplesse/2872" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">5 secondes pour coller des DM tout en souplesse</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Loctite 4902 est un nouvel adhésif cyanoacrylate mono-composant à faible viscosité, qui épouse parfaitement tout type de support (plastiques, caoutchoucs, métaux…) et polymérise en 5 secondes.
Développé pour assurer notamment le collage de dispositifs médicaux à [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/materiaux/adhesifs/5-secondes-pour-coller-des-dm-tout-en-souplesse/2872" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/assemblage-sous-traitance-et-services/pour-des-tubes-et-raccords-medicaux-proprement-colles/2870" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/04/Syneo.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/assemblage-sous-traitance-et-services/pour-des-tubes-et-raccords-medicaux-proprement-colles/2870" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Syneo</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/assemblage-sous-traitance-et-services/pour-des-tubes-et-raccords-medicaux-proprement-colles/2870" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Pour des tubes et raccords médicaux proprement collés</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Face aux inconvénients du cyanoacrylate dans le collage des cathéters, sondes, et autres tubulures médicales, Syneo a développé une solution à base d’adhésif UV micro-dosé. Le résultat obtenu concilie propreté, vitesse et précision.&nbsp;
Généralement utilisé pour [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/assemblage-sous-traitance-et-services/pour-des-tubes-et-raccords-medicaux-proprement-colles/2870" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/comparateur-optique-sans-contact/2864" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/04/Stil-S.A.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/comparateur-optique-sans-contact/2864" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Stil S.A</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/comparateur-optique-sans-contact/2864" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Comparateur optique sans contact</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">L’imagerie confocale chromatique offre de multiples applications médicales : mesure de la cornée, métrologie 3D sur le vivant, contrôle dimensionnel des stents… Inventeur de ce principe, Stil SA a mis au point un appareil de [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/equipements-de-production-et-techniques-de-fabrication/metrologie_controle/comparateur-optique-sans-contact/2864" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/composants-oem/electriques_electroniques/alimentation-de-30-watts-ultra-compacte-pour-le-medical/2830" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/04/XP-Power.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/electriques_electroniques/alimentation-de-30-watts-ultra-compacte-pour-le-medical/2830" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">XP Power</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/electriques_electroniques/alimentation-de-30-watts-ultra-compacte-pour-le-medical/2830" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Alimentation de 30 Watts ultra-compacte pour le médical</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;"> Conformes aux normes de sécurité en vigueur dans le médical, les alimentations de la série ELM30 de XP Power affichent le plus petit encombrement du marché pour des modèles AC/DC mono-tension de 30W, avec [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/electriques_electroniques/alimentation-de-30-watts-ultra-compacte-pour-le-medical/2830" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>

</tbody></table><!----><table width="704" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:0px" id="footer"><tbody><tr><td style="font-family:Arial; font-size:12px"><table cellspacing="0" width="702"><tbody><tr><td style="padding-bottom:10px;padding-top:10px;padding-left:10px;padding-right:10px;background-color:#c7c7c7"><table width="700"><tbody><tr><td align="left"><a href="http://news.vogel.de/inxmail2/d?q00wueoq0eqfngbii000000000000000ietwqbri3277"><img src="http://www.devicemed.fr/wp-content/themes/devicemed-responsive/images/newsletter/nl20/vogel_logo.gif" alt="Vogel Logo"></a></td><td align="right"></td></tr></tbody></table></td></tr><!----><tr><td align="center" style="font-size:11px;font-family:Arial,Helvetica,sans-serif;padding:10px;background-color:#d2d2d2;text-align:center;"><a style="text-decoration:none;" href="http://www.devicemed.fr/nous-contacter"><span style="font-size:12px;color:#b30f1d;text-align:center;">Contact</span></a></td></tr><!----><tr><td style="PADDING-BOTTOM: 10px; PADDING-TOP: 10px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; BACKGROUND-COLOR: #616161"><p style="FONT-SIZE: 11px; FONT-FAMILY: Arial, Helvetica, sans-serif; COLOR: #ffffff; LINE-HEIGHT: 18px">© The French language edition of DeviceMed is a publication of Evelyne Gisselbrecht, licensed by Vogel Business Media GmbH &amp; Co. KG, 97082 Wuerzburg/Germany.<br>

© Copyright of the trademark « DeviceMed » by Vogel Business Media GmbH &amp; Co. KG, 97082 Wuerzburg/Germany.<br>

Responsable du contenu rédactionnel sur <a style="text-decoration:none;color:#fff;" href="http://www.devicemed.fr/">www.devicemed.fr</a> : Evelyne Gisselbrecht, éditrice de DeviceMed, 33 rue du Puy-de-Dôme, 63370 Lempdes France</p></td></tr></tbody></table><!----><p></p></td></tr><tr><td style="text-align:center;font-family:Arial;font-size:11px">Le bulletin est adressé à <?php echo $mail; ?></td></tr>

<tr style="font-family:Arial;font-size:11px;color:#005ea8;text-decoration:underline;text-align:center;"><td><a style="text-decoration:none;" href="http://www.devicemed.fr/newsletter/desinscrire/<?php echo $mail; ?>"><span>Se désabonner</span></a></td></tr></tbody></table></td><td width="10" valign="top"></td><td width="160" valign="top"><table style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;"><tbody><tr><td style="padding-bottom:10px;"><a target="_blank" href="http://www.device-med.fr/?url=http://www.devicemed.de/&amp;id=28"><img src="http://www.device-med.fr/wp-content/uploads/newsletter/devicemed_de.jpg" width="127px"></a></td></tr>

<tr><td><div style="width:100%;padding-top:15px;"><a href="http://www.devicemed.fr/suppliers/" target="_blank">

<img width="127px" src="http://www.devicemed.fr/wp-content/uploads/newsletter/repertoirev6.jpg"></a></div></td></tr></tbody></table></td></tr></tbody></table></div>