<?php
	if(isset($_GET['mail']) && $_GET['mail'] != '') {
		$mail = $_GET['mail'];
	}
?>
<div style="width:850px !important;margin:0 auto;"><table cellspacing="0" cellpadding="0" width="850" border="0" align="center" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin:auto;" id="wrapper"><tbody><tr><td width="700" valign="top" style="background-color:#F1F1F1"><table style="border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt;margin-left:10px;" width="700"><tbody><tr><td><a style="border:none" href="http://www.devicemed.fr/"><img width="700" height="91" title="logo" alt="newsletter" src="http://www.device-med.fr/wp-content/uploads/newsletter/original.jpg"></a></td></tr></tbody></table><table style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;margin-left:10px;margin-top:10px;margin-bottom:10px;" width="700" id="top_news"><tbody><tr><td align="center"><a target="_blank" href="http://www.device-med.fr/?url=http://ubifrance-events.com/ris/?xtor=AD-717&amp;id=41"><img src="http://devicemed.fr/wp-content/uploads/newsletter/ubifrance.png" border="0" alt="" style="width:468px;text-align:center;"></a></td></tr> </tbody></table>

<table style="border-collapse:collapse;border-top:1px dotted #555;mso-table-lspace:0pt; mso-table-rspace:0pt;margin-left:10px;margin-top:10px;" width="700" id="top_news"><tbody><tr><td align="left"><h1 style="font-size:20px;color:#000000;font-family:Arial;">Sommaire de la newsletter du 26 mai 2015</h1></td></tr> </tbody></table><table width="700" style="border-bottom:0;border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:10px;" id="inhaltsverzeichnis"><tbody><tr><td><ul style="padding-left:20px;margin-top:0px;margin-bottom:0;">

<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/materiaux/adhesifs/pansements-intelligents-mieux-vaut-prevenir/3324" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Techtera&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/materiaux/adhesifs/pansements-intelligents-mieux-vaut-prevenir/3324" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Pansements intelligents : mieux vaut prévenir…</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/watson-marlow-pumps-group-change-de-nom-et-acquiert-asepco/3070" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">WMFTG&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/watson-marlow-pumps-group-change-de-nom-et-acquiert-asepco/3070" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Watson-Marlow Pumps Group change de nom et acquiert Asepco</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/le-laboratoire-gilbert-choisit-stiplastics-pour-fabriquer-son-mouche-bebe/3336" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Stiplastics&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/le-laboratoire-gilbert-choisit-stiplastics-pour-fabriquer-son-mouche-bebe/3336" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Le Laboratoire Gilbert choisit Stiplastics pour fabriquer son mouche-bébé</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/le-medtech-village-se-developpe-sur-ephj-epmt-smt/3344" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">BioAlps&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/le-medtech-village-se-developpe-sur-ephj-epmt-smt/3344" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Le Medtech Village se développe sur EPHJ-EPMT-SMT</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/moteurs-et-entrainements/entrainements-dc-sur-mesure-configurables-en-ligne/3298" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">maxon motor&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/moteurs-et-entrainements/entrainements-dc-sur-mesure-configurables-en-ligne/3298" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Entrainements DC sur mesure configurables en ligne</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/les-cros-axonal-et-biostatem-fusionnent-avec-un-objectif-de-croissance-ambitieux/3349" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Axonal-Biostatem&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/les-cros-axonal-et-biostatem-fusionnent-avec-un-objectif-de-croissance-ambitieux/3349" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Les CROs Axonal et Biostatem fusionnent avec un objectif de croissance ambitieux</span></a></li><!---->


<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/electronique/certifications-iso-14001-et-iso-9001-pour-globe-technologies-et-atems/3307" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;color:#333333 !important;">Altrics&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/electronique/certifications-iso-14001-et-iso-9001-pour-globe-technologies-et-atems/3307" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Certifications ISO 14001 et ISO 9001 pour Globe Technologies et Atems</span></a></li><!---->

</ul></td></tr></tbody></table>

<table width="700" style="margin-top:10px;border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:10px;" id="content"><tbody>

<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/materiaux/adhesifs/pansements-intelligents-mieux-vaut-prevenir/3324" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/05/UC-Berkeley-e1432558305245.jpeg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/materiaux/adhesifs/pansements-intelligents-mieux-vaut-prevenir/3324" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Techtera</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/materiaux/adhesifs/pansements-intelligents-mieux-vaut-prevenir/3324" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Pansements intelligents : mieux vaut prévenir…</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Capables de détecter l’infection d’une plaie, de mesurer sa cicatrisation, ou encore de détecter la formation d’escarres, les pansements intelligents ne sont plus très loin d’être commercialisés. Les recherches avancent en effet à grands pas.
Voici [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/materiaux/adhesifs/pansements-intelligents-mieux-vaut-prevenir/3324" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/watson-marlow-pumps-group-change-de-nom-et-acquiert-asepco/3070" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/05/Watson-Marlow-Fluid-Technology-Group.png"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/watson-marlow-pumps-group-change-de-nom-et-acquiert-asepco/3070" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">WMFTG</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/watson-marlow-pumps-group-change-de-nom-et-acquiert-asepco/3070" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Watson-Marlow Pumps Group change de nom et acquiert Asepco</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Début mars, le groupe Spirax-Sarco Engineering plc a rebaptisé sa filiale Watson-Marlow Fluid Technology Group.&nbsp;Cette entité est aujourd’hui renforcée&nbsp;avec l’acquisition de l’Américain Asepco, spécialisé dans les vannes aseptiques et les mélangeurs magnétiques pour l’industrie des [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/watson-marlow-pumps-group-change-de-nom-et-acquiert-asepco/3070" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td colspan="2" style="border-top:1px dotted #555;padding-left:90px;"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;margin-top:10px;"><span style="font-size:12px;font-family:Helvetica,Arial,sans-serif;color:#999;">Annonce</span></p></td></tr><tr><td colspan="2" width="128" valign="top" style="width:128px;padding-bottom: 10px;padding-left:90px;">

<div style="padding:10px;width:500px;border:1px solid #333;">

<a href="http://www.device-med.fr/?url=http://www.ni.com/medical/f/?cid=Advertising-701i0000001KXrJAAW-France-none&amp;metc=mt34pe&amp;id=42" target="_blank"><img style="border:solid 1px #FFFFFF;padding-right:10px;" width="100" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/newsletter/ni_nl_25-05-2015.jpg"></a>

<p style="margin:0px;padding-left:140px;"><a style="margin:0px;text-decoration:none;" href="http://www.device-med.fr/?url=http://www.ni.com/medical/f/?cid=Advertising-701i0000001KXrJAAW-France-none&amp;metc=mt34pe&amp;id=42" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:black;">Solutions NI pour les dispositifs médicaux</span></a></p>

<p style="padding-left:140px;font-size:12px;line-height:21px;font-family:Arial;color:#333;margin:0px;">National Instruments fournit les outils et la technologie nécessaires pour prototyper et déployer votre dispositif médical. 

Les plateformes de prototypage NI associent le logiciel de programmation graphique LabVIEW, des technologies FPGA et des E/S analogiques, afin d'assurer une grande précision et fiabilité.

<a style="text-decoration:none;" href="http://www.device-med.fr/?url=http://www.ni.com/medical/f/?cid=Advertising-701i0000001KXrJAAW-France-none&amp;metc=mt34pe&amp;id=42" target="_blank"><span style="color:#005ea8;">Pour en savoir plus</span></a></p></div></td></tr>

<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/le-laboratoire-gilbert-choisit-stiplastics-pour-fabriquer-son-mouche-bebe/3336" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/05/Stiplastics.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/le-laboratoire-gilbert-choisit-stiplastics-pour-fabriquer-son-mouche-bebe/3336" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Stiplastics</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/le-laboratoire-gilbert-choisit-stiplastics-pour-fabriquer-son-mouche-bebe/3336" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Le Laboratoire Gilbert choisit Stiplastics pour fabriquer son mouche-bébé</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Fabricant de DM à base de matière plastique injectée, Stiplastics met son expérience du développement B-to-C au service de produits en B-to-B. La PME fabriquera ainsi le mouche-bébé du laboratoire Gilbert sous la marque Physiodose.
Filiale [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/le-laboratoire-gilbert-choisit-stiplastics-pour-fabriquer-son-mouche-bebe/3336" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/evenements/le-medtech-village-se-developpe-sur-ephj-epmt-smt/3344" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/05/BioAlps.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/le-medtech-village-se-developpe-sur-ephj-epmt-smt/3344" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">BioAlps</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/le-medtech-village-se-developpe-sur-ephj-epmt-smt/3344" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Le Medtech Village se développe sur EPHJ-EPMT-SMT</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Le «&nbsp;MedTech Village&nbsp;» reprend ses quartiers dans le secteur du salon genevois dédié aux technologies médicales. Avec davantage de surface, d’exposants et d’animations, il devient un passage obligé pour les visiteurs fabricants de DM.
Organisé par [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/evenements/le-medtech-village-se-developpe-sur-ephj-epmt-smt/3344" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/composants-oem/moteurs-et-entrainements/entrainements-dc-sur-mesure-configurables-en-ligne/3298" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/05/Maxon-Motor.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/moteurs-et-entrainements/entrainements-dc-sur-mesure-configurables-en-ligne/3298" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">maxon motor</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/moteurs-et-entrainements/entrainements-dc-sur-mesure-configurables-en-ligne/3298" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Entrainements DC sur mesure configurables en ligne</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Maxon motor enrichit sa gamme X drivers d’un micro-moteur de 12 mm de diamètre.&nbsp;L’entreprise propose à ses clients de définir directement sur le web tous les paramètres de son système d’entrainement, du bobinage au codeur, [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/moteurs-et-entrainements/entrainements-dc-sur-mesure-configurables-en-ligne/3298" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td colspan="2" style="border-top:1px dotted #555;padding-left:90px;"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;margin-top:10px;"><span style="font-size:12px;font-family:Helvetica,Arial,sans-serif;color:#999;">Annonce</span></p></td></tr><tr><td colspan="2" width="128" valign="top" style="width:128px;padding-bottom: 10px;padding-left:90px;">

<div style="padding:10px;width:500px;border:1px solid #333;">

<a href="http://www.device-med.fr/?url=http://www.vaisala.fr/fr/lifescience/continuous-monitoring/Pages/default.aspx?utm_medium=referral&amp;utm_source=DeviceMed&amp;utm_campaign=CEN-LSC-EMEA-FR-Device%20Med&amp;utm_content=CMS&amp;id=43" target="_blank"><img style="border:solid 1px #FFFFFF;padding-right:10px;" width="100" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/newsletter/vaisela_nl_26-05-2015.jpg"></a>

<p style="margin:0px;padding-left:140px;"><a style="margin:0px;text-decoration:none;" href="http://www.device-med.fr/?url=http://www.vaisala.fr/fr/lifescience/continuous-monitoring/Pages/default.aspx?utm_medium=referral&amp;utm_source=DeviceMed&amp;utm_campaign=CEN-LSC-EMEA-FR-Device%20Med&amp;utm_content=CMS&amp;id=43" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:black;">Monitoring pour les environnements contrôlés</span></a></p>

<p style="padding-left:140px;font-size:12px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Conçu pour les environnements contrôlés dans les industries de santé, le Système de Monitoring Vaisala fournit en continu des données de température, humidité et autres paramètres tout en garantissant la totale conformité réglementaire. 

Pour plus d’informations visitez nous sur <a style="text-decoration:none;" href="http://www.device-med.fr/?url=http://www.medteceurope.com/fr/france&amp;id=44" target="_blank">Medtec France</a> ou <a style="text-decoration:none;" href="http://www.device-med.fr/?url=http://www.vaisala.fr/fr/lifescience/continuous-monitoring/Pages/default.aspx?utm_medium=referral&amp;utm_source=DeviceMed&amp;utm_campaign=CEN-LSC-EMEA-FR-Device%20Med&amp;utm_content=CMS&amp;id=43" target="_blank">cliquez ici</a>.

</p></div></td></tr>

<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/les-cros-axonal-et-biostatem-fusionnent-avec-un-objectif-de-croissance-ambitieux/3349" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/05/Axonal3.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/les-cros-axonal-et-biostatem-fusionnent-avec-un-objectif-de-croissance-ambitieux/3349" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Axonal-Biostatem</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/les-cros-axonal-et-biostatem-fusionnent-avec-un-objectif-de-croissance-ambitieux/3349" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Les CROs Axonal et Biostatem fusionnent avec un objectif de croissance ambitieux</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Spécialisées dans la recherche clinique, Axonal et Biostatem annoncent leur fusion, qui donne naissance à un leader en Europe sur les activités d’évaluation post-AMM (Autorisation de Mise sur le Marché) des produits de santé.
En fusionnant [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/vie-des-entreprises/les-cros-axonal-et-biostatem-fusionnent-avec-un-objectif-de-croissance-ambitieux/3349" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>


<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/electronique/certifications-iso-14001-et-iso-9001-pour-globe-technologies-et-atems/3307" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/05/Altrics.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/electronique/certifications-iso-14001-et-iso-9001-pour-globe-technologies-et-atems/3307" target="_blank">

<span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Altrics</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/electronique/certifications-iso-14001-et-iso-9001-pour-globe-technologies-et-atems/3307" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Certifications ISO 14001 et ISO 9001 pour Globe Technologies et Atems</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Après avoir inauguré un site de production au Portugal, le groupe Altrics annonce l’obtention du certificat ISO 14001 et le renouvellement du certificat ISO 9001 pour ses filiales Globe Technologies et Atems.
Sous-traitant électronique de cartes [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/sous-traitance-et-services/electronique/certifications-iso-14001-et-iso-9001-pour-globe-technologies-et-atems/3307" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>

</tbody></table><!----><table width="704" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:0px" id="footer"><tbody><tr><td style="font-family:Arial; font-size:12px"><table cellspacing="0" width="702"><tbody><tr><td style="padding-bottom:10px;padding-top:10px;padding-left:10px;padding-right:10px;background-color:#c7c7c7"><table width="700"><tbody><tr><td align="left"><a href="http://news.vogel.de/inxmail2/d?q00wueoq0eqfngbii000000000000000ietwqbri3277"><img src="http://www.devicemed.fr/wp-content/themes/devicemed-responsive/images/newsletter/nl20/vogel_logo.gif" alt="Vogel Logo"></a></td><td align="right"></td></tr></tbody></table></td></tr><!----><tr><td align="center" style="font-size:11px;font-family:Arial,Helvetica,sans-serif;padding:10px;background-color:#d2d2d2;text-align:center;"><a style="text-decoration:none;" href="http://www.devicemed.fr/nous-contacter"><span style="font-size:12px;color:#b30f1d;text-align:center;">Contact</span></a></td></tr><!----><tr><td style="PADDING-BOTTOM: 10px; PADDING-TOP: 10px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; BACKGROUND-COLOR: #616161"><p style="FONT-SIZE: 11px; FONT-FAMILY: Arial, Helvetica, sans-serif; COLOR: #ffffff; LINE-HEIGHT: 18px">© The French language edition of DeviceMed is a publication of Evelyne Gisselbrecht, licensed by Vogel Business Media GmbH &amp; Co. KG, 97082 Wuerzburg/Germany.<br>

© Copyright of the trademark « DeviceMed » by Vogel Business Media GmbH &amp; Co. KG, 97082 Wuerzburg/Germany.<br>

Responsable du contenu rédactionnel sur <a style="text-decoration:none;color:#fff;" href="http://www.devicemed.fr/">www.devicemed.fr</a> : Evelyne Gisselbrecht, éditrice de DeviceMed, 33 rue du Puy-de-Dôme, 63370 Lempdes France</p></td></tr></tbody></table><!----><p></p></td></tr><tr><td style="text-align:center;font-family:Arial;font-size:11px">Le bulletin est adressé à <?php echo $mail; ?></td></tr>

<tr style="font-family:Arial;font-size:11px;color:#005ea8;text-decoration:underline;text-align:center;"><td><a style="text-decoration:none;" href="http://www.devicemed.fr/newsletter/desinscrire/<?php echo $mail; ?>"><span>Se désabonner</span></a></td></tr></tbody></table></td><td width="10" valign="top"></td><td width="160" valign="top"><table style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;"><tbody><tr><td style="padding-bottom:10px;"><a target="_blank" href="http://www.device-med.fr/?url=http://www.devicemed.de/&amp;id=40"><img src="http://www.device-med.fr/wp-content/uploads/newsletter/devicemed_de.jpg" width="127px"></a></td></tr>

<tr><td><div style="width:100%;padding-top:15px;"><a href="http://www.devicemed.fr/wp-content/uploads/archives/pdf/003_gesamt.pdf" target="_blank">

<img width="127px" src="http://devicemed.fr/wp-content/uploads/newsletter/pave_magazine.png"></a></div></td></tr></tbody></table></td></tr></tbody></table></div>