<?php
	if(isset($_GET['mail']) && $_GET['mail'] != '') {
		$mail = $_GET['mail'];
	}
?>
<div style="width:850px !important;margin:0 auto;"><table cellspacing="0" cellpadding="0" width="850" border="0" align="center" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin:auto;" id="wrapper"><tbody><tr><td width="700" valign="top" style="background-color:#F1F1F1"><table style="border-collapse:collapse;mso-table-lspace:0pt;mso-table-rspace:0pt;margin-left:10px;" width="700"><tbody><tr><td><a style="border:none" href="http://www.devicemed.fr/"><img width="700" height="91" title="logo" alt="newsletter" src="http://www.device-med.fr/wp-content/uploads/newsletter/original.jpg"></a></td></tr></tbody></table><table style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;margin-left:10px;margin-top:10px;margin-bottom:10px;" width="700" id="top_news"><tbody><tr><td align="center"><a target="_blank" href="http://www.knf.fr/produits/pompes-de-laboratoire/"><img src="http://devicemed.fr/wp-content/uploads/newsletter/knf.gif" border="0" alt="" style="margin-top:5px;width:468px;text-align:center;"></a></td></tr> </tbody></table><table style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;margin-left:10px;margin-top:10px;border-top:1px dotted #555;" width="700" id="top_news"><tbody><tr><td align="left"><h1 style="font-size:20px;color:#000000;font-family:Arial;">Sommaire de la newsletter du 3 février 2015</h1></td></tr> </tbody></table><table width="700" style="border-bottom:0;border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:10px;" id="inhaltsverzeichnis"><tbody><tr><td><ul style="padding-left:20px;margin-top:0px;margin-bottom:0;"><li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/le-groupe-auvergnat-omerin-rachete-la-societe-union-plastic/2394" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;">Omerin Câbles SAS&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/le-groupe-auvergnat-omerin-rachete-la-societe-union-plastic/2394" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Rachat de la société Union Plastic par le groupe auvergnat Omerin</span></a></li><!---->

<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/capteur-de-debit-miniature-a-usage-unique/2384" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;">Sensirion&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/capteur-de-debit-miniature-a-usage-unique/2384" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Capteur de débit miniature à usage unique</span></a></li><!---->

<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/watson-marlow-acquiert-biopure-fabricant-de-dm-a-usage-unique/2396" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;">Watson Marlow&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/watson-marlow-acquiert-biopure-fabricant-de-dm-a-usage-unique/2396" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Watson Marlow acquiert BioPure, fabricant de DM à usage unique</span></a></li><!---->

<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/guide-dondes-creux-en-silice-a-faisceau-de-visee/2391" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;">Molex&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/guide-dondes-creux-en-silice-a-faisceau-de-visee/2391" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Guide d’ondes creux en silice à faisceau de visée</span></a></li><!---->

<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/vis-miniatures-formees-a-froid/2388" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;">Eichenberger Gewinde&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/vis-miniatures-formees-a-froid/2388" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Vis miniatures formées à froid</span></a></li><!---->

<li style="font-family:Arial;"><a style="color:#333333;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/alimentation-acdc-compacte-de-360-w-pour-applications-medicales/2373" target="_blank"><span style="color:#333333;font-size:14px;line-height:19px;text-decoration:none;">Artesyn&nbsp;- </span></a><!----><a style="color:#005ea8;font-size:14px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/alimentation-acdc-compacte-de-360-w-pour-applications-medicales/2373" target="_blank"><span style="color:#005ea8;font-size:14px;line-height:19px;text-decoration:none;">Alimentation AC/DC compacte de 360 W pour applications médicales</span></a></li><!---->

</ul></td></tr></tbody></table>

<table width="700" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:10px" id="content"><tbody><tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/le-groupe-auvergnat-omerin-rachete-la-societe-union-plastic/2394" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/02/Union-Plastic.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/le-groupe-auvergnat-omerin-rachete-la-societe-union-plastic/2394" target="_blank"><span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Omerin Câbles SAS</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/le-groupe-auvergnat-omerin-rachete-la-societe-union-plastic/2394" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Rachat de la société Union Plastic par le groupe auvergnat Omerin</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Le Groupe français Omerin vient de signer l’acquisition de la totalité des parts sociales de la société Union Plastic, un pionnier dans la conception et la fabrication de dispositifs médicaux et emballages primaires pharmaceutiques en [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/le-groupe-auvergnat-omerin-rachete-la-societe-union-plastic/2394" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>

<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/composants-oem/capteur-de-debit-miniature-a-usage-unique/2384" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/02/Sensirion.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/capteur-de-debit-miniature-a-usage-unique/2384" target="_blank"><span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Sensirion</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/capteur-de-debit-miniature-a-usage-unique/2384" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Capteur de débit miniature à usage unique</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Lauréat du prix de l’innovation décerné lors de la dernière édition du salon Compamed par nos collègues allemands de DeviceMed, ce capteur à usage unique intègre une puce qui permet de mesurer le flux de [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/capteur-de-debit-miniature-a-usage-unique/2384" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>

<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/actualites/watson-marlow-acquiert-biopure-fabricant-de-dm-a-usage-unique/2396" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/02/Watson-Marlow.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/watson-marlow-acquiert-biopure-fabricant-de-dm-a-usage-unique/2396" target="_blank"><span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Watson Marlow</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/watson-marlow-acquiert-biopure-fabricant-de-dm-a-usage-unique/2396" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Watson Marlow acquiert BioPure, fabricant de DM à usage unique</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Watson-Marlow Pumps Group,&nbsp;acteur clé mondial de la technologie des pompes péristaltiques, a annoncé l’acquisition de la société britannique BioPure technologie, spécialisée dans la conception et la fabrication d’accessoires de composants biopharmaceutiques à usage unique.
Les tubes [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/actualites/watson-marlow-acquiert-biopure-fabricant-de-dm-a-usage-unique/2396" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>

<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/composants-oem/guide-dondes-creux-en-silice-a-faisceau-de-visee/2391" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/02/Molex.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/guide-dondes-creux-en-silice-a-faisceau-de-visee/2391" target="_blank"><span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Molex</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/guide-dondes-creux-en-silice-a-faisceau-de-visee/2391" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Guide d’ondes creux en silice à faisceau de visée</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Destiné à être intégré dans des sondes portatives et autres équipements de thérapie au laser dans le bloc opératoire, ce guide d’ondes spécialisé intègre la distribution de puissance laser moyen infrarouge et l’alignement du faisceau [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/guide-dondes-creux-en-silice-a-faisceau-de-visee/2391" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>

<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/composants-oem/vis-miniatures-formees-a-froid/2388" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/02/Eichenberger.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/vis-miniatures-formees-a-froid/2388" target="_blank"><span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Eichenberger Gewinde</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/vis-miniatures-formees-a-froid/2388" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Vis miniatures formées à froid</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">Avec un diamètre de tige filetée de 4 mm et un pas de 1 mm, les vis à billes roulées miniatures Carry 4×1 proposées par Eichenberger Gewinde s’adressent au marché des équipements médicaux en demande [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/vis-miniatures-formees-a-froid/2388" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>

<tr><td width="128" valign="top" style="width:128px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555;"><a href="http://www.devicemed.fr/dossiers/composants-oem/alimentation-acdc-compacte-de-360-w-pour-applications-medicales/2373" target="_blank"><img style="border:solid 1px #FFFFFF;" width="120" height="auto" align="left" alt="img6" src="http://www.devicemed.fr/wp-content/uploads/2015/02/Artesyn.jpg"></a></td><td style="width:557px;padding-bottom:15px;padding-top:10px;border-top:1px dotted #555" width="557" valign="top"><p style="line-height:9.5pt;mso-line-height-rule:exactly;margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/alimentation-acdc-compacte-de-360-w-pour-applications-medicales/2373" target="_blank"><span style="font-size:12px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#333333;">Artesyn</span></a></p>

<p style="margin:0px;"><a style="margin:0px;text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/alimentation-acdc-compacte-de-360-w-pour-applications-medicales/2373" target="_blank"><span style="font-size:16px;font-weight:bold;font-family:Helvetica,Arial,sans-serif;color:#005ea8;">Alimentation AC/DC compacte de 360 W pour applications médicales</span></a></p><p style="font-size:14px;line-height:21px;font-family:Arial;color:#333;margin:0px;">
Conforme à la norme de sécurité EN60601-1 relative aux matériels médicaux, l’alimentation AC/DC LPS360-M d’Artesyn Embedded Technologies offre une puissance de 360 W sur une sortie (12, 15, 24 ou 48 V) dans un encombrement [...]<a style="text-decoration:none;" href="http://www.devicemed.fr/dossiers/composants-oem/alimentation-acdc-compacte-de-360-w-pour-applications-medicales/2373" target="_blank"><span style="color:#005ea8;">Lire la suite</span></a></p></td></tr>

</tbody></table><!----><table width="704" style="border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt; margin-left:0px" id="footer"><tbody><tr><td style="font-family:Arial; font-size:12px"><table cellspacing="0" width="702"><tbody><tr><td style="padding-bottom:10px;padding-top:10px;padding-left:10px;padding-right:10px;background-color:#c7c7c7"><table width="700"><tbody><tr><td align="left"><a href="http://news.vogel.de/inxmail2/d?q00wueoq0eqfngbii000000000000000ietwqbri3277"><img src="http://www.devicemed.fr/wp-content/themes/devicemed-responsive/images/newsletter/nl20/vogel_logo.gif" alt="Vogel Logo"></a></td><td align="right"></td></tr></tbody></table></td></tr><!----><tr><td align="center" style="font-size:11px;font-family:Arial,Helvetica,sans-serif;padding:10px;background-color:#d2d2d2;text-align:center;"><a style="text-decoration:none;" href="http://www.devicemed.fr/nous-contacter"><span style="font-size:12px;color:#b30f1d;text-align:center;">Contact</span></a></td></tr><!----><tr><td style="PADDING-BOTTOM: 10px; PADDING-TOP: 10px; PADDING-LEFT: 10px; PADDING-RIGHT: 10px; BACKGROUND-COLOR: #616161"><p style="FONT-SIZE: 11px; FONT-FAMILY: Arial, Helvetica, sans-serif; COLOR: #ffffff; LINE-HEIGHT: 18px">© The French language edition of DeviceMed is a publication of Evelyne Gisselbrecht, licensed by Vogel Business Media GmbH &amp; Co. KG, 97082 Wuerzburg/Germany.<br>

© Copyright of the trademark « DeviceMed » by Vogel Business Media GmbH &amp; Co. KG, 97082 Wuerzburg/Germany.<br>

Responsable du contenu rédactionnel sur <a style="text-decoration:none;color:#fff;" href="http://www.devicemed.fr/">www.devicemed.fr</a> : Evelyne Gisselbrecht, éditrice de DeviceMed, 33 rue du Puy-de-Dôme, 63370 Lempdes France</p></td></tr></tbody></table><!----><p></p></td></tr><tr><td style="text-align:center;font-family:Arial;font-size:11px">Le bulletin est adressé à <?php echo $mail; ?></td></tr>

<tr style="font-family:Arial;font-size:11px;color:#005ea8;text-decoration:underline;text-align:center;"><td><a style="text-decoration:none;" href="http://www.devicemed.fr/newsletter/desinscrire/<?php echo $mail; ?>"><span>Se désabonner</span></a></td></tr></tbody></table></td><td width="10" valign="top"></td><td width="160" valign="top"><table style="border-top:0px dotted #555;border-collapse:collapse; mso-table-lspace:0pt; mso-table-rspace:0pt;"><tbody><tr><td><a href="http://www.ni.com/virtualbench/try/f/?cid=Advertising-Measurements-France-none&amp;metc=mt2tge"><img src="http://www.device-med.fr/wp-content/uploads/newsletter/ni2.gif" width="127px"></a></td></tr></tbody></table></td></tr></tbody></table></div>